// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationClaim.proto

package Proj.Proto;

public final class LocationClaimProto {
  private LocationClaimProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationClaim_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationClaim_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_SignedLocationClaim_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_SignedLocationClaim_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023LocationClaim.proto\022\nProj.Proto\032\017signa" +
      "ture.proto\032\021Observation.proto\032\016Location." +
      "proto\"\226\001\n\rLocationClaim\022\017\n\007claimId\030\001 \001(\t" +
      "\022\020\n\010proverId\030\002 \001(\t\022&\n\010location\030\003 \001(\0132\024.P" +
      "roj.Proto.Location\022\014\n\004time\030\004 \001(\005\022,\n\013obse" +
      "rvation\030\005 \001(\0132\027.Proj.Proto.Observation\"o" +
      "\n\023SignedLocationClaim\022(\n\005claim\030\001 \001(\0132\031.P" +
      "roj.Proto.LocationClaim\022.\n\017proverSignatu" +
      "re\030\002 \001(\0132\025.Proj.Proto.SignatureB\"\n\nProj." +
      "ProtoB\022LocationClaimProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Proj.Proto.SignatureProto.getDescriptor(),
          Proj.Proto.ObservationProto.getDescriptor(),
          Proj.Proto.LocationProto.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_LocationClaim_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_LocationClaim_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationClaim_descriptor,
        new java.lang.String[] { "ClaimId", "ProverId", "Location", "Time", "Observation", });
    internal_static_Proj_Proto_SignedLocationClaim_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Proj_Proto_SignedLocationClaim_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_SignedLocationClaim_descriptor,
        new java.lang.String[] { "Claim", "ProverSignature", });
    Proj.Proto.SignatureProto.getDescriptor();
    Proj.Proto.ObservationProto.getDescriptor();
    Proj.Proto.LocationProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
