// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package Proj.Proto;

public interface TimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.Time)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  boolean hasTimestamp();
  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <pre>
   * timestamp
   * </pre>
   *
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <pre>
   * interval defined by two timestamps
   * </pre>
   *
   * <code>.Proj.Proto.TimeInterval interval = 2;</code>
   */
  boolean hasInterval();
  /**
   * <pre>
   * interval defined by two timestamps
   * </pre>
   *
   * <code>.Proj.Proto.TimeInterval interval = 2;</code>
   */
  Proj.Proto.TimeInterval getInterval();
  /**
   * <pre>
   * interval defined by two timestamps
   * </pre>
   *
   * <code>.Proj.Proto.TimeInterval interval = 2;</code>
   */
  Proj.Proto.TimeIntervalOrBuilder getIntervalOrBuilder();

  /**
   * <pre>
   * time relative to epoch
   * </pre>
   *
   * <code>.Proj.Proto.EpochTime relativeToEpoch = 3;</code>
   */
  boolean hasRelativeToEpoch();
  /**
   * <pre>
   * time relative to epoch
   * </pre>
   *
   * <code>.Proj.Proto.EpochTime relativeToEpoch = 3;</code>
   */
  Proj.Proto.EpochTime getRelativeToEpoch();
  /**
   * <pre>
   * time relative to epoch
   * </pre>
   *
   * <code>.Proj.Proto.EpochTime relativeToEpoch = 3;</code>
   */
  Proj.Proto.EpochTimeOrBuilder getRelativeToEpochOrBuilder();

  /**
   * <pre>
   * use when we do no have time information
   * </pre>
   *
   * <code>.google.protobuf.Empty empty = 4;</code>
   */
  boolean hasEmpty();
  /**
   * <pre>
   * use when we do no have time information
   * </pre>
   *
   * <code>.google.protobuf.Empty empty = 4;</code>
   */
  com.google.protobuf.Empty getEmpty();
  /**
   * <pre>
   * use when we do no have time information
   * </pre>
   *
   * <code>.google.protobuf.Empty empty = 4;</code>
   */
  com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder();

  public Proj.Proto.Time.TimeCase getTimeCase();
}
