// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientService.proto

package Proj.Services;

public final class ClientServiceOuterClass {
  private ClientServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_ClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_ClientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientService.proto\022\nProj.Proto\032\023Locat" +
      "ionClaim.proto\"?\n\016ClientResponse\022\027\n\017resp" +
      "onseMessage\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\0052" +
      "^\n\rClientService\022M\n\024receiveLocationClaim" +
      "\022\031.Proj.Proto.LocationClaim\032\032.Proj.Proto" +
      ".ClientResponseB\021\n\rProj.ServicesP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Proj.Proto.LocationClaimProto.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_ClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_ClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_ClientResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    Proj.Proto.LocationClaimProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
