// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wi_fi.proto

package Proj.Proto.wi_fi;

public interface WiFiNetworksEvidenceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.wi_fi.WiFiNetworksEvidence)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unique id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <pre>
   * unique id
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .Proj.Proto.wi_fi.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  java.util.List<Proj.Proto.wi_fi.WiFiNetworksEvidence.AP> 
      getApsList();
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .Proj.Proto.wi_fi.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  Proj.Proto.wi_fi.WiFiNetworksEvidence.AP getAps(int index);
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .Proj.Proto.wi_fi.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  int getApsCount();
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .Proj.Proto.wi_fi.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  java.util.List<? extends Proj.Proto.wi_fi.WiFiNetworksEvidence.APOrBuilder> 
      getApsOrBuilderList();
  /**
   * <pre>
   * detected APs
   * </pre>
   *
   * <code>repeated .Proj.Proto.wi_fi.WiFiNetworksEvidence.AP aps = 2;</code>
   */
  Proj.Proto.wi_fi.WiFiNetworksEvidence.APOrBuilder getApsOrBuilder(
      int index);
}
