// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CollectedData.proto

package proj_contract.proto;

public final class CollectedDataProto {
  private CollectedDataProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_Position_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_Position_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_Entity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_Entity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_Entities_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_Entities_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023CollectedData.proto\022\nProj.Proto\"2\n\010Pos" +
      "ition\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 \001(\005\022\020\n\010timestep\030" +
      "\003 \001(\005\"8\n\006Entity\022\014\n\004type\030\001 \001(\t\022\t\n\001x\030\002 \001(\005" +
      "\022\t\n\001y\030\003 \001(\005\022\n\n\002id\030\004 \001(\t\".\n\010Entities\022\"\n\006e" +
      "ntity\030\001 \003(\0132\022.Proj.Proto.EntityB+\n\023proj_" +
      "contract.protoB\022CollectedDataProtoP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Proj_Proto_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_Position_descriptor,
        new java.lang.String[] { "X", "Y", "Timestep", });
    internal_static_Proj_Proto_Entity_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Proj_Proto_Entity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_Entity_descriptor,
        new java.lang.String[] { "Type", "X", "Y", "Id", });
    internal_static_Proj_Proto_Entities_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Proj_Proto_Entities_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_Entities_descriptor,
        new java.lang.String[] { "Entity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
