// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package proj_contract.proto;

public interface CoordinatesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.Coordinates)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   */
  int getY();
}
