// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationEndorsement.proto

package proj_contract.proto;

public interface EncryptedLocationEndorsementRequestWithIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.EncryptedLocationEndorsementRequestWithId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
   */
  boolean hasEncryptedLocationEndorsementRequest();
  /**
   * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
   */
  proj_contract.proto.EncryptedLocationEndorsementRequest getEncryptedLocationEndorsementRequest();
  /**
   * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
   */
  proj_contract.proto.EncryptedLocationEndorsementRequestOrBuilder getEncryptedLocationEndorsementRequestOrBuilder();

  /**
   * <code>int32 receiverId = 2;</code>
   */
  int getReceiverId();
}
