// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationEndorsement.proto

package proj_contract.proto;

/**
 * Protobuf type {@code Proj.Proto.EncryptedLocationEndorsementRequestWithId}
 */
public  final class EncryptedLocationEndorsementRequestWithId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Proj.Proto.EncryptedLocationEndorsementRequestWithId)
    EncryptedLocationEndorsementRequestWithIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EncryptedLocationEndorsementRequestWithId.newBuilder() to construct.
  private EncryptedLocationEndorsementRequestWithId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EncryptedLocationEndorsementRequestWithId() {
    receiverId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EncryptedLocationEndorsementRequestWithId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            proj_contract.proto.EncryptedLocationEndorsementRequest.Builder subBuilder = null;
            if (encryptedLocationEndorsementRequest_ != null) {
              subBuilder = encryptedLocationEndorsementRequest_.toBuilder();
            }
            encryptedLocationEndorsementRequest_ = input.readMessage(proj_contract.proto.EncryptedLocationEndorsementRequest.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(encryptedLocationEndorsementRequest_);
              encryptedLocationEndorsementRequest_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            receiverId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proj_contract.proto.LocationEndorsementOuterClass.internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proj_contract.proto.LocationEndorsementOuterClass.internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proj_contract.proto.EncryptedLocationEndorsementRequestWithId.class, proj_contract.proto.EncryptedLocationEndorsementRequestWithId.Builder.class);
  }

  public static final int ENCRYPTEDLOCATIONENDORSEMENTREQUEST_FIELD_NUMBER = 1;
  private proj_contract.proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest_;
  /**
   * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
   */
  public boolean hasEncryptedLocationEndorsementRequest() {
    return encryptedLocationEndorsementRequest_ != null;
  }
  /**
   * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
   */
  public proj_contract.proto.EncryptedLocationEndorsementRequest getEncryptedLocationEndorsementRequest() {
    return encryptedLocationEndorsementRequest_ == null ? proj_contract.proto.EncryptedLocationEndorsementRequest.getDefaultInstance() : encryptedLocationEndorsementRequest_;
  }
  /**
   * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
   */
  public proj_contract.proto.EncryptedLocationEndorsementRequestOrBuilder getEncryptedLocationEndorsementRequestOrBuilder() {
    return getEncryptedLocationEndorsementRequest();
  }

  public static final int RECEIVERID_FIELD_NUMBER = 2;
  private int receiverId_;
  /**
   * <code>int32 receiverId = 2;</code>
   */
  public int getReceiverId() {
    return receiverId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (encryptedLocationEndorsementRequest_ != null) {
      output.writeMessage(1, getEncryptedLocationEndorsementRequest());
    }
    if (receiverId_ != 0) {
      output.writeInt32(2, receiverId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (encryptedLocationEndorsementRequest_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEncryptedLocationEndorsementRequest());
    }
    if (receiverId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, receiverId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proj_contract.proto.EncryptedLocationEndorsementRequestWithId)) {
      return super.equals(obj);
    }
    proj_contract.proto.EncryptedLocationEndorsementRequestWithId other = (proj_contract.proto.EncryptedLocationEndorsementRequestWithId) obj;

    boolean result = true;
    result = result && (hasEncryptedLocationEndorsementRequest() == other.hasEncryptedLocationEndorsementRequest());
    if (hasEncryptedLocationEndorsementRequest()) {
      result = result && getEncryptedLocationEndorsementRequest()
          .equals(other.getEncryptedLocationEndorsementRequest());
    }
    result = result && (getReceiverId()
        == other.getReceiverId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEncryptedLocationEndorsementRequest()) {
      hash = (37 * hash) + ENCRYPTEDLOCATIONENDORSEMENTREQUEST_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedLocationEndorsementRequest().hashCode();
    }
    hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
    hash = (53 * hash) + getReceiverId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proj_contract.proto.EncryptedLocationEndorsementRequestWithId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Proj.Proto.EncryptedLocationEndorsementRequestWithId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Proj.Proto.EncryptedLocationEndorsementRequestWithId)
      proj_contract.proto.EncryptedLocationEndorsementRequestWithIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proj_contract.proto.LocationEndorsementOuterClass.internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proj_contract.proto.LocationEndorsementOuterClass.internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proj_contract.proto.EncryptedLocationEndorsementRequestWithId.class, proj_contract.proto.EncryptedLocationEndorsementRequestWithId.Builder.class);
    }

    // Construct using proj_contract.proto.EncryptedLocationEndorsementRequestWithId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (encryptedLocationEndorsementRequestBuilder_ == null) {
        encryptedLocationEndorsementRequest_ = null;
      } else {
        encryptedLocationEndorsementRequest_ = null;
        encryptedLocationEndorsementRequestBuilder_ = null;
      }
      receiverId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proj_contract.proto.LocationEndorsementOuterClass.internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_descriptor;
    }

    @java.lang.Override
    public proj_contract.proto.EncryptedLocationEndorsementRequestWithId getDefaultInstanceForType() {
      return proj_contract.proto.EncryptedLocationEndorsementRequestWithId.getDefaultInstance();
    }

    @java.lang.Override
    public proj_contract.proto.EncryptedLocationEndorsementRequestWithId build() {
      proj_contract.proto.EncryptedLocationEndorsementRequestWithId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proj_contract.proto.EncryptedLocationEndorsementRequestWithId buildPartial() {
      proj_contract.proto.EncryptedLocationEndorsementRequestWithId result = new proj_contract.proto.EncryptedLocationEndorsementRequestWithId(this);
      if (encryptedLocationEndorsementRequestBuilder_ == null) {
        result.encryptedLocationEndorsementRequest_ = encryptedLocationEndorsementRequest_;
      } else {
        result.encryptedLocationEndorsementRequest_ = encryptedLocationEndorsementRequestBuilder_.build();
      }
      result.receiverId_ = receiverId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proj_contract.proto.EncryptedLocationEndorsementRequestWithId) {
        return mergeFrom((proj_contract.proto.EncryptedLocationEndorsementRequestWithId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proj_contract.proto.EncryptedLocationEndorsementRequestWithId other) {
      if (other == proj_contract.proto.EncryptedLocationEndorsementRequestWithId.getDefaultInstance()) return this;
      if (other.hasEncryptedLocationEndorsementRequest()) {
        mergeEncryptedLocationEndorsementRequest(other.getEncryptedLocationEndorsementRequest());
      }
      if (other.getReceiverId() != 0) {
        setReceiverId(other.getReceiverId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proj_contract.proto.EncryptedLocationEndorsementRequestWithId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proj_contract.proto.EncryptedLocationEndorsementRequestWithId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private proj_contract.proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        proj_contract.proto.EncryptedLocationEndorsementRequest, proj_contract.proto.EncryptedLocationEndorsementRequest.Builder, proj_contract.proto.EncryptedLocationEndorsementRequestOrBuilder> encryptedLocationEndorsementRequestBuilder_;
    /**
     * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
     */
    public boolean hasEncryptedLocationEndorsementRequest() {
      return encryptedLocationEndorsementRequestBuilder_ != null || encryptedLocationEndorsementRequest_ != null;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
     */
    public proj_contract.proto.EncryptedLocationEndorsementRequest getEncryptedLocationEndorsementRequest() {
      if (encryptedLocationEndorsementRequestBuilder_ == null) {
        return encryptedLocationEndorsementRequest_ == null ? proj_contract.proto.EncryptedLocationEndorsementRequest.getDefaultInstance() : encryptedLocationEndorsementRequest_;
      } else {
        return encryptedLocationEndorsementRequestBuilder_.getMessage();
      }
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
     */
    public Builder setEncryptedLocationEndorsementRequest(proj_contract.proto.EncryptedLocationEndorsementRequest value) {
      if (encryptedLocationEndorsementRequestBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        encryptedLocationEndorsementRequest_ = value;
        onChanged();
      } else {
        encryptedLocationEndorsementRequestBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
     */
    public Builder setEncryptedLocationEndorsementRequest(
        proj_contract.proto.EncryptedLocationEndorsementRequest.Builder builderForValue) {
      if (encryptedLocationEndorsementRequestBuilder_ == null) {
        encryptedLocationEndorsementRequest_ = builderForValue.build();
        onChanged();
      } else {
        encryptedLocationEndorsementRequestBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
     */
    public Builder mergeEncryptedLocationEndorsementRequest(proj_contract.proto.EncryptedLocationEndorsementRequest value) {
      if (encryptedLocationEndorsementRequestBuilder_ == null) {
        if (encryptedLocationEndorsementRequest_ != null) {
          encryptedLocationEndorsementRequest_ =
            proj_contract.proto.EncryptedLocationEndorsementRequest.newBuilder(encryptedLocationEndorsementRequest_).mergeFrom(value).buildPartial();
        } else {
          encryptedLocationEndorsementRequest_ = value;
        }
        onChanged();
      } else {
        encryptedLocationEndorsementRequestBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
     */
    public Builder clearEncryptedLocationEndorsementRequest() {
      if (encryptedLocationEndorsementRequestBuilder_ == null) {
        encryptedLocationEndorsementRequest_ = null;
        onChanged();
      } else {
        encryptedLocationEndorsementRequest_ = null;
        encryptedLocationEndorsementRequestBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
     */
    public proj_contract.proto.EncryptedLocationEndorsementRequest.Builder getEncryptedLocationEndorsementRequestBuilder() {
      
      onChanged();
      return getEncryptedLocationEndorsementRequestFieldBuilder().getBuilder();
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
     */
    public proj_contract.proto.EncryptedLocationEndorsementRequestOrBuilder getEncryptedLocationEndorsementRequestOrBuilder() {
      if (encryptedLocationEndorsementRequestBuilder_ != null) {
        return encryptedLocationEndorsementRequestBuilder_.getMessageOrBuilder();
      } else {
        return encryptedLocationEndorsementRequest_ == null ?
            proj_contract.proto.EncryptedLocationEndorsementRequest.getDefaultInstance() : encryptedLocationEndorsementRequest_;
      }
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationEndorsementRequest encryptedLocationEndorsementRequest = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proj_contract.proto.EncryptedLocationEndorsementRequest, proj_contract.proto.EncryptedLocationEndorsementRequest.Builder, proj_contract.proto.EncryptedLocationEndorsementRequestOrBuilder> 
        getEncryptedLocationEndorsementRequestFieldBuilder() {
      if (encryptedLocationEndorsementRequestBuilder_ == null) {
        encryptedLocationEndorsementRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proj_contract.proto.EncryptedLocationEndorsementRequest, proj_contract.proto.EncryptedLocationEndorsementRequest.Builder, proj_contract.proto.EncryptedLocationEndorsementRequestOrBuilder>(
                getEncryptedLocationEndorsementRequest(),
                getParentForChildren(),
                isClean());
        encryptedLocationEndorsementRequest_ = null;
      }
      return encryptedLocationEndorsementRequestBuilder_;
    }

    private int receiverId_ ;
    /**
     * <code>int32 receiverId = 2;</code>
     */
    public int getReceiverId() {
      return receiverId_;
    }
    /**
     * <code>int32 receiverId = 2;</code>
     */
    public Builder setReceiverId(int value) {
      
      receiverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 receiverId = 2;</code>
     */
    public Builder clearReceiverId() {
      
      receiverId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Proj.Proto.EncryptedLocationEndorsementRequestWithId)
  }

  // @@protoc_insertion_point(class_scope:Proj.Proto.EncryptedLocationEndorsementRequestWithId)
  private static final proj_contract.proto.EncryptedLocationEndorsementRequestWithId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proj_contract.proto.EncryptedLocationEndorsementRequestWithId();
  }

  public static proj_contract.proto.EncryptedLocationEndorsementRequestWithId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EncryptedLocationEndorsementRequestWithId>
      PARSER = new com.google.protobuf.AbstractParser<EncryptedLocationEndorsementRequestWithId>() {
    @java.lang.Override
    public EncryptedLocationEndorsementRequestWithId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EncryptedLocationEndorsementRequestWithId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EncryptedLocationEndorsementRequestWithId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EncryptedLocationEndorsementRequestWithId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proj_contract.proto.EncryptedLocationEndorsementRequestWithId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

