// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationEndorsement.proto

package proj_contract.proto;

public interface EncryptedLocationEndorsementRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.EncryptedLocationEndorsementRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>bytes initializationVector = 2;</code>
   */
  com.google.protobuf.ByteString getInitializationVector();
}
