// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationClaim.proto

package proj_contract.proto;

/**
 * Protobuf type {@code Proj.Proto.EncryptedLocationClaimWithId}
 */
public  final class EncryptedLocationClaimWithId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Proj.Proto.EncryptedLocationClaimWithId)
    EncryptedLocationClaimWithIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EncryptedLocationClaimWithId.newBuilder() to construct.
  private EncryptedLocationClaimWithId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EncryptedLocationClaimWithId() {
    receiverId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EncryptedLocationClaimWithId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            proj_contract.proto.EncryptedLocationClaim.Builder subBuilder = null;
            if (encryptedLocationClaim_ != null) {
              subBuilder = encryptedLocationClaim_.toBuilder();
            }
            encryptedLocationClaim_ = input.readMessage(proj_contract.proto.EncryptedLocationClaim.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(encryptedLocationClaim_);
              encryptedLocationClaim_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            receiverId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_EncryptedLocationClaimWithId_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_EncryptedLocationClaimWithId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proj_contract.proto.EncryptedLocationClaimWithId.class, proj_contract.proto.EncryptedLocationClaimWithId.Builder.class);
  }

  public static final int ENCRYPTEDLOCATIONCLAIM_FIELD_NUMBER = 1;
  private proj_contract.proto.EncryptedLocationClaim encryptedLocationClaim_;
  /**
   * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
   */
  public boolean hasEncryptedLocationClaim() {
    return encryptedLocationClaim_ != null;
  }
  /**
   * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
   */
  public proj_contract.proto.EncryptedLocationClaim getEncryptedLocationClaim() {
    return encryptedLocationClaim_ == null ? proj_contract.proto.EncryptedLocationClaim.getDefaultInstance() : encryptedLocationClaim_;
  }
  /**
   * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
   */
  public proj_contract.proto.EncryptedLocationClaimOrBuilder getEncryptedLocationClaimOrBuilder() {
    return getEncryptedLocationClaim();
  }

  public static final int RECEIVERID_FIELD_NUMBER = 2;
  private int receiverId_;
  /**
   * <code>int32 receiverId = 2;</code>
   */
  public int getReceiverId() {
    return receiverId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (encryptedLocationClaim_ != null) {
      output.writeMessage(1, getEncryptedLocationClaim());
    }
    if (receiverId_ != 0) {
      output.writeInt32(2, receiverId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (encryptedLocationClaim_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getEncryptedLocationClaim());
    }
    if (receiverId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, receiverId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proj_contract.proto.EncryptedLocationClaimWithId)) {
      return super.equals(obj);
    }
    proj_contract.proto.EncryptedLocationClaimWithId other = (proj_contract.proto.EncryptedLocationClaimWithId) obj;

    boolean result = true;
    result = result && (hasEncryptedLocationClaim() == other.hasEncryptedLocationClaim());
    if (hasEncryptedLocationClaim()) {
      result = result && getEncryptedLocationClaim()
          .equals(other.getEncryptedLocationClaim());
    }
    result = result && (getReceiverId()
        == other.getReceiverId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasEncryptedLocationClaim()) {
      hash = (37 * hash) + ENCRYPTEDLOCATIONCLAIM_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedLocationClaim().hashCode();
    }
    hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
    hash = (53 * hash) + getReceiverId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proj_contract.proto.EncryptedLocationClaimWithId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proj_contract.proto.EncryptedLocationClaimWithId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Proj.Proto.EncryptedLocationClaimWithId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Proj.Proto.EncryptedLocationClaimWithId)
      proj_contract.proto.EncryptedLocationClaimWithIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_EncryptedLocationClaimWithId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_EncryptedLocationClaimWithId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proj_contract.proto.EncryptedLocationClaimWithId.class, proj_contract.proto.EncryptedLocationClaimWithId.Builder.class);
    }

    // Construct using proj_contract.proto.EncryptedLocationClaimWithId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (encryptedLocationClaimBuilder_ == null) {
        encryptedLocationClaim_ = null;
      } else {
        encryptedLocationClaim_ = null;
        encryptedLocationClaimBuilder_ = null;
      }
      receiverId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_EncryptedLocationClaimWithId_descriptor;
    }

    @java.lang.Override
    public proj_contract.proto.EncryptedLocationClaimWithId getDefaultInstanceForType() {
      return proj_contract.proto.EncryptedLocationClaimWithId.getDefaultInstance();
    }

    @java.lang.Override
    public proj_contract.proto.EncryptedLocationClaimWithId build() {
      proj_contract.proto.EncryptedLocationClaimWithId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proj_contract.proto.EncryptedLocationClaimWithId buildPartial() {
      proj_contract.proto.EncryptedLocationClaimWithId result = new proj_contract.proto.EncryptedLocationClaimWithId(this);
      if (encryptedLocationClaimBuilder_ == null) {
        result.encryptedLocationClaim_ = encryptedLocationClaim_;
      } else {
        result.encryptedLocationClaim_ = encryptedLocationClaimBuilder_.build();
      }
      result.receiverId_ = receiverId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proj_contract.proto.EncryptedLocationClaimWithId) {
        return mergeFrom((proj_contract.proto.EncryptedLocationClaimWithId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proj_contract.proto.EncryptedLocationClaimWithId other) {
      if (other == proj_contract.proto.EncryptedLocationClaimWithId.getDefaultInstance()) return this;
      if (other.hasEncryptedLocationClaim()) {
        mergeEncryptedLocationClaim(other.getEncryptedLocationClaim());
      }
      if (other.getReceiverId() != 0) {
        setReceiverId(other.getReceiverId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proj_contract.proto.EncryptedLocationClaimWithId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proj_contract.proto.EncryptedLocationClaimWithId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private proj_contract.proto.EncryptedLocationClaim encryptedLocationClaim_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        proj_contract.proto.EncryptedLocationClaim, proj_contract.proto.EncryptedLocationClaim.Builder, proj_contract.proto.EncryptedLocationClaimOrBuilder> encryptedLocationClaimBuilder_;
    /**
     * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
     */
    public boolean hasEncryptedLocationClaim() {
      return encryptedLocationClaimBuilder_ != null || encryptedLocationClaim_ != null;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
     */
    public proj_contract.proto.EncryptedLocationClaim getEncryptedLocationClaim() {
      if (encryptedLocationClaimBuilder_ == null) {
        return encryptedLocationClaim_ == null ? proj_contract.proto.EncryptedLocationClaim.getDefaultInstance() : encryptedLocationClaim_;
      } else {
        return encryptedLocationClaimBuilder_.getMessage();
      }
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
     */
    public Builder setEncryptedLocationClaim(proj_contract.proto.EncryptedLocationClaim value) {
      if (encryptedLocationClaimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        encryptedLocationClaim_ = value;
        onChanged();
      } else {
        encryptedLocationClaimBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
     */
    public Builder setEncryptedLocationClaim(
        proj_contract.proto.EncryptedLocationClaim.Builder builderForValue) {
      if (encryptedLocationClaimBuilder_ == null) {
        encryptedLocationClaim_ = builderForValue.build();
        onChanged();
      } else {
        encryptedLocationClaimBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
     */
    public Builder mergeEncryptedLocationClaim(proj_contract.proto.EncryptedLocationClaim value) {
      if (encryptedLocationClaimBuilder_ == null) {
        if (encryptedLocationClaim_ != null) {
          encryptedLocationClaim_ =
            proj_contract.proto.EncryptedLocationClaim.newBuilder(encryptedLocationClaim_).mergeFrom(value).buildPartial();
        } else {
          encryptedLocationClaim_ = value;
        }
        onChanged();
      } else {
        encryptedLocationClaimBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
     */
    public Builder clearEncryptedLocationClaim() {
      if (encryptedLocationClaimBuilder_ == null) {
        encryptedLocationClaim_ = null;
        onChanged();
      } else {
        encryptedLocationClaim_ = null;
        encryptedLocationClaimBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
     */
    public proj_contract.proto.EncryptedLocationClaim.Builder getEncryptedLocationClaimBuilder() {
      
      onChanged();
      return getEncryptedLocationClaimFieldBuilder().getBuilder();
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
     */
    public proj_contract.proto.EncryptedLocationClaimOrBuilder getEncryptedLocationClaimOrBuilder() {
      if (encryptedLocationClaimBuilder_ != null) {
        return encryptedLocationClaimBuilder_.getMessageOrBuilder();
      } else {
        return encryptedLocationClaim_ == null ?
            proj_contract.proto.EncryptedLocationClaim.getDefaultInstance() : encryptedLocationClaim_;
      }
    }
    /**
     * <code>.Proj.Proto.EncryptedLocationClaim encryptedLocationClaim = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proj_contract.proto.EncryptedLocationClaim, proj_contract.proto.EncryptedLocationClaim.Builder, proj_contract.proto.EncryptedLocationClaimOrBuilder> 
        getEncryptedLocationClaimFieldBuilder() {
      if (encryptedLocationClaimBuilder_ == null) {
        encryptedLocationClaimBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proj_contract.proto.EncryptedLocationClaim, proj_contract.proto.EncryptedLocationClaim.Builder, proj_contract.proto.EncryptedLocationClaimOrBuilder>(
                getEncryptedLocationClaim(),
                getParentForChildren(),
                isClean());
        encryptedLocationClaim_ = null;
      }
      return encryptedLocationClaimBuilder_;
    }

    private int receiverId_ ;
    /**
     * <code>int32 receiverId = 2;</code>
     */
    public int getReceiverId() {
      return receiverId_;
    }
    /**
     * <code>int32 receiverId = 2;</code>
     */
    public Builder setReceiverId(int value) {
      
      receiverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 receiverId = 2;</code>
     */
    public Builder clearReceiverId() {
      
      receiverId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Proj.Proto.EncryptedLocationClaimWithId)
  }

  // @@protoc_insertion_point(class_scope:Proj.Proto.EncryptedLocationClaimWithId)
  private static final proj_contract.proto.EncryptedLocationClaimWithId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proj_contract.proto.EncryptedLocationClaimWithId();
  }

  public static proj_contract.proto.EncryptedLocationClaimWithId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EncryptedLocationClaimWithId>
      PARSER = new com.google.protobuf.AbstractParser<EncryptedLocationClaimWithId>() {
    @java.lang.Override
    public EncryptedLocationClaimWithId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EncryptedLocationClaimWithId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EncryptedLocationClaimWithId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EncryptedLocationClaimWithId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proj_contract.proto.EncryptedLocationClaimWithId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

