// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CollectedData.proto

package proj_contract.proto;

public interface EntitiesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.Entities)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  java.util.List<proj_contract.proto.Entity> 
      getEntityList();
  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  proj_contract.proto.Entity getEntity(int index);
  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  int getEntityCount();
  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  java.util.List<? extends proj_contract.proto.EntityOrBuilder> 
      getEntityOrBuilderList();
  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  proj_contract.proto.EntityOrBuilder getEntityOrBuilder(
      int index);
}
