// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CollectedData.proto

package proj_contract.proto;

/**
 * Protobuf type {@code Proj.Proto.Entities}
 */
public  final class Entities extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Proj.Proto.Entities)
    EntitiesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Entities.newBuilder() to construct.
  private Entities(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Entities() {
    entity_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Entities(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              entity_ = new java.util.ArrayList<proj_contract.proto.Entity>();
              mutable_bitField0_ |= 0x00000001;
            }
            entity_.add(
                input.readMessage(proj_contract.proto.Entity.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        entity_ = java.util.Collections.unmodifiableList(entity_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proj_contract.proto.CollectedDataProto.internal_static_Proj_Proto_Entities_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proj_contract.proto.CollectedDataProto.internal_static_Proj_Proto_Entities_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proj_contract.proto.Entities.class, proj_contract.proto.Entities.Builder.class);
  }

  public static final int ENTITY_FIELD_NUMBER = 1;
  private java.util.List<proj_contract.proto.Entity> entity_;
  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  public java.util.List<proj_contract.proto.Entity> getEntityList() {
    return entity_;
  }
  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  public java.util.List<? extends proj_contract.proto.EntityOrBuilder> 
      getEntityOrBuilderList() {
    return entity_;
  }
  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  public int getEntityCount() {
    return entity_.size();
  }
  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  public proj_contract.proto.Entity getEntity(int index) {
    return entity_.get(index);
  }
  /**
   * <code>repeated .Proj.Proto.Entity entity = 1;</code>
   */
  public proj_contract.proto.EntityOrBuilder getEntityOrBuilder(
      int index) {
    return entity_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < entity_.size(); i++) {
      output.writeMessage(1, entity_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < entity_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, entity_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proj_contract.proto.Entities)) {
      return super.equals(obj);
    }
    proj_contract.proto.Entities other = (proj_contract.proto.Entities) obj;

    boolean result = true;
    result = result && getEntityList()
        .equals(other.getEntityList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEntityCount() > 0) {
      hash = (37 * hash) + ENTITY_FIELD_NUMBER;
      hash = (53 * hash) + getEntityList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proj_contract.proto.Entities parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.Entities parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.Entities parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.Entities parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.Entities parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.Entities parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.Entities parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proj_contract.proto.Entities parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proj_contract.proto.Entities parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proj_contract.proto.Entities parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proj_contract.proto.Entities parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proj_contract.proto.Entities parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proj_contract.proto.Entities prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Proj.Proto.Entities}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Proj.Proto.Entities)
      proj_contract.proto.EntitiesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proj_contract.proto.CollectedDataProto.internal_static_Proj_Proto_Entities_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proj_contract.proto.CollectedDataProto.internal_static_Proj_Proto_Entities_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proj_contract.proto.Entities.class, proj_contract.proto.Entities.Builder.class);
    }

    // Construct using proj_contract.proto.Entities.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEntityFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (entityBuilder_ == null) {
        entity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        entityBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proj_contract.proto.CollectedDataProto.internal_static_Proj_Proto_Entities_descriptor;
    }

    @java.lang.Override
    public proj_contract.proto.Entities getDefaultInstanceForType() {
      return proj_contract.proto.Entities.getDefaultInstance();
    }

    @java.lang.Override
    public proj_contract.proto.Entities build() {
      proj_contract.proto.Entities result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proj_contract.proto.Entities buildPartial() {
      proj_contract.proto.Entities result = new proj_contract.proto.Entities(this);
      int from_bitField0_ = bitField0_;
      if (entityBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          entity_ = java.util.Collections.unmodifiableList(entity_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.entity_ = entity_;
      } else {
        result.entity_ = entityBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proj_contract.proto.Entities) {
        return mergeFrom((proj_contract.proto.Entities)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proj_contract.proto.Entities other) {
      if (other == proj_contract.proto.Entities.getDefaultInstance()) return this;
      if (entityBuilder_ == null) {
        if (!other.entity_.isEmpty()) {
          if (entity_.isEmpty()) {
            entity_ = other.entity_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEntityIsMutable();
            entity_.addAll(other.entity_);
          }
          onChanged();
        }
      } else {
        if (!other.entity_.isEmpty()) {
          if (entityBuilder_.isEmpty()) {
            entityBuilder_.dispose();
            entityBuilder_ = null;
            entity_ = other.entity_;
            bitField0_ = (bitField0_ & ~0x00000001);
            entityBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEntityFieldBuilder() : null;
          } else {
            entityBuilder_.addAllMessages(other.entity_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proj_contract.proto.Entities parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proj_contract.proto.Entities) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<proj_contract.proto.Entity> entity_ =
      java.util.Collections.emptyList();
    private void ensureEntityIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        entity_ = new java.util.ArrayList<proj_contract.proto.Entity>(entity_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        proj_contract.proto.Entity, proj_contract.proto.Entity.Builder, proj_contract.proto.EntityOrBuilder> entityBuilder_;

    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public java.util.List<proj_contract.proto.Entity> getEntityList() {
      if (entityBuilder_ == null) {
        return java.util.Collections.unmodifiableList(entity_);
      } else {
        return entityBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public int getEntityCount() {
      if (entityBuilder_ == null) {
        return entity_.size();
      } else {
        return entityBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public proj_contract.proto.Entity getEntity(int index) {
      if (entityBuilder_ == null) {
        return entity_.get(index);
      } else {
        return entityBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public Builder setEntity(
        int index, proj_contract.proto.Entity value) {
      if (entityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityIsMutable();
        entity_.set(index, value);
        onChanged();
      } else {
        entityBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public Builder setEntity(
        int index, proj_contract.proto.Entity.Builder builderForValue) {
      if (entityBuilder_ == null) {
        ensureEntityIsMutable();
        entity_.set(index, builderForValue.build());
        onChanged();
      } else {
        entityBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public Builder addEntity(proj_contract.proto.Entity value) {
      if (entityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityIsMutable();
        entity_.add(value);
        onChanged();
      } else {
        entityBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public Builder addEntity(
        int index, proj_contract.proto.Entity value) {
      if (entityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEntityIsMutable();
        entity_.add(index, value);
        onChanged();
      } else {
        entityBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public Builder addEntity(
        proj_contract.proto.Entity.Builder builderForValue) {
      if (entityBuilder_ == null) {
        ensureEntityIsMutable();
        entity_.add(builderForValue.build());
        onChanged();
      } else {
        entityBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public Builder addEntity(
        int index, proj_contract.proto.Entity.Builder builderForValue) {
      if (entityBuilder_ == null) {
        ensureEntityIsMutable();
        entity_.add(index, builderForValue.build());
        onChanged();
      } else {
        entityBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public Builder addAllEntity(
        java.lang.Iterable<? extends proj_contract.proto.Entity> values) {
      if (entityBuilder_ == null) {
        ensureEntityIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, entity_);
        onChanged();
      } else {
        entityBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public Builder clearEntity() {
      if (entityBuilder_ == null) {
        entity_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        entityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public Builder removeEntity(int index) {
      if (entityBuilder_ == null) {
        ensureEntityIsMutable();
        entity_.remove(index);
        onChanged();
      } else {
        entityBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public proj_contract.proto.Entity.Builder getEntityBuilder(
        int index) {
      return getEntityFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public proj_contract.proto.EntityOrBuilder getEntityOrBuilder(
        int index) {
      if (entityBuilder_ == null) {
        return entity_.get(index);  } else {
        return entityBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public java.util.List<? extends proj_contract.proto.EntityOrBuilder> 
         getEntityOrBuilderList() {
      if (entityBuilder_ != null) {
        return entityBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(entity_);
      }
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public proj_contract.proto.Entity.Builder addEntityBuilder() {
      return getEntityFieldBuilder().addBuilder(
          proj_contract.proto.Entity.getDefaultInstance());
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public proj_contract.proto.Entity.Builder addEntityBuilder(
        int index) {
      return getEntityFieldBuilder().addBuilder(
          index, proj_contract.proto.Entity.getDefaultInstance());
    }
    /**
     * <code>repeated .Proj.Proto.Entity entity = 1;</code>
     */
    public java.util.List<proj_contract.proto.Entity.Builder> 
         getEntityBuilderList() {
      return getEntityFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        proj_contract.proto.Entity, proj_contract.proto.Entity.Builder, proj_contract.proto.EntityOrBuilder> 
        getEntityFieldBuilder() {
      if (entityBuilder_ == null) {
        entityBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            proj_contract.proto.Entity, proj_contract.proto.Entity.Builder, proj_contract.proto.EntityOrBuilder>(
                entity_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        entity_ = null;
      }
      return entityBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Proj.Proto.Entities)
  }

  // @@protoc_insertion_point(class_scope:Proj.Proto.Entities)
  private static final proj_contract.proto.Entities DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proj_contract.proto.Entities();
  }

  public static proj_contract.proto.Entities getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Entities>
      PARSER = new com.google.protobuf.AbstractParser<Entities>() {
    @java.lang.Override
    public Entities parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Entities(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Entities> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Entities> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proj_contract.proto.Entities getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

