// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package proj_contract.proto;

public interface EntitiesDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.EntitiesData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Proj.Proto.EntityData entityData = 1;</code>
   */
  java.util.List<proj_contract.proto.EntityData> 
      getEntityDataList();
  /**
   * <code>repeated .Proj.Proto.EntityData entityData = 1;</code>
   */
  proj_contract.proto.EntityData getEntityData(int index);
  /**
   * <code>repeated .Proj.Proto.EntityData entityData = 1;</code>
   */
  int getEntityDataCount();
  /**
   * <code>repeated .Proj.Proto.EntityData entityData = 1;</code>
   */
  java.util.List<? extends proj_contract.proto.EntityDataOrBuilder> 
      getEntityDataOrBuilderList();
  /**
   * <code>repeated .Proj.Proto.EntityData entityData = 1;</code>
   */
  proj_contract.proto.EntityDataOrBuilder getEntityDataOrBuilder(
      int index);
}
