// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationEndorsement.proto

package proj_contract.proto;

public final class LocationEndorsementOuterClass {
  private LocationEndorsementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationEndorsementRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationEndorsementRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationEndorsementRequestWithId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationEndorsementRequestWithId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationEndorsement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationEndorsement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationEndorsementWithId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationEndorsementWithId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031LocationEndorsement.proto\022\nProj.Proto\032" +
      "\nData.proto\032\023LocationClaim.proto\"c\n\032Loca" +
      "tionEndorsementRequest\0220\n\rlocationClaim\030" +
      "\001 \001(\0132\031.Proj.Proto.LocationClaim\022\023\n\013requ" +
      "esterId\030\002 \001(\005\"\202\001\n LocationEndorsementReq" +
      "uestWithId\022J\n\032locationEndorsementRequest" +
      "\030\001 \001(\0132&.Proj.Proto.LocationEndorsementR" +
      "equest\022\022\n\nreceiverId\030\002 \001(\005\"\211\001\n\023LocationE" +
      "ndorsement\022\021\n\twitnessId\030\001 \001(\005\022\017\n\007claimId" +
      "\030\002 \001(\005\022\020\n\010proverId\030\003 \001(\005\022\020\n\010timestep\030\004 \001" +
      "(\005\022*\n\nentityData\030\005 \001(\0132\026.Proj.Proto.Enti" +
      "tyData\"m\n\031LocationEndorsementWithId\022<\n\023l" +
      "ocationEndorsement\030\001 \001(\0132\037.Proj.Proto.Lo" +
      "cationEndorsement\022\022\n\nreceiverId\030\002 \001(\005B\027\n" +
      "\023proj_contract.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proj_contract.proto.Data.getDescriptor(),
          proj_contract.proto.LocationClaimOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_LocationEndorsementRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_LocationEndorsementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationEndorsementRequest_descriptor,
        new java.lang.String[] { "LocationClaim", "RequesterId", });
    internal_static_Proj_Proto_LocationEndorsementRequestWithId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Proj_Proto_LocationEndorsementRequestWithId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationEndorsementRequestWithId_descriptor,
        new java.lang.String[] { "LocationEndorsementRequest", "ReceiverId", });
    internal_static_Proj_Proto_LocationEndorsement_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Proj_Proto_LocationEndorsement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationEndorsement_descriptor,
        new java.lang.String[] { "WitnessId", "ClaimId", "ProverId", "Timestep", "EntityData", });
    internal_static_Proj_Proto_LocationEndorsementWithId_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Proj_Proto_LocationEndorsementWithId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationEndorsementWithId_descriptor,
        new java.lang.String[] { "LocationEndorsement", "ReceiverId", });
    proj_contract.proto.Data.getDescriptor();
    proj_contract.proto.LocationClaimOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
