// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationEndorsement.proto

package proj_contract.proto;

public interface LocationEndorsementRequestWithIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.LocationEndorsementRequestWithId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Proj.Proto.LocationEndorsementRequest locationEndorsementRequest = 1;</code>
   */
  boolean hasLocationEndorsementRequest();
  /**
   * <code>.Proj.Proto.LocationEndorsementRequest locationEndorsementRequest = 1;</code>
   */
  proj_contract.proto.LocationEndorsementRequest getLocationEndorsementRequest();
  /**
   * <code>.Proj.Proto.LocationEndorsementRequest locationEndorsementRequest = 1;</code>
   */
  proj_contract.proto.LocationEndorsementRequestOrBuilder getLocationEndorsementRequestOrBuilder();

  /**
   * <code>int32 receiverId = 2;</code>
   */
  int getReceiverId();
}
