// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationClaim.proto

package proj_contract.proto;

public interface LocationClaimWithIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.LocationClaimWithId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
   */
  boolean hasLocationClaim();
  /**
   * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
   */
  proj_contract.proto.LocationClaim getLocationClaim();
  /**
   * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
   */
  proj_contract.proto.LocationClaimOrBuilder getLocationClaimOrBuilder();

  /**
   * <code>int32 receiverId = 2;</code>
   */
  int getReceiverId();
}
