// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationEndorsement.proto

package proj_contract.proto;

public interface LocationEndorsementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.LocationEndorsement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 witnessId = 1;</code>
   */
  int getWitnessId();

  /**
   * <code>int32 claimId = 2;</code>
   */
  int getClaimId();

  /**
   * <code>int32 proverId = 3;</code>
   */
  int getProverId();

  /**
   * <code>int32 timestep = 4;</code>
   */
  int getTimestep();

  /**
   * <code>.Proj.Proto.EntityData entityData = 5;</code>
   */
  boolean hasEntityData();
  /**
   * <code>.Proj.Proto.EntityData entityData = 5;</code>
   */
  proj_contract.proto.EntityData getEntityData();
  /**
   * <code>.Proj.Proto.EntityData entityData = 5;</code>
   */
  proj_contract.proto.EntityDataOrBuilder getEntityDataOrBuilder();
}
