// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationEndorsement.proto

package proj_contract.proto;

public final class LocationEndorsementOuterClass {
  private LocationEndorsementOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationEndorsementRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationEndorsementRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_EncryptedLocationEndorsementRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_EncryptedLocationEndorsementRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationEndorsement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationEndorsement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_EncryptedLocationEndorsement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_EncryptedLocationEndorsement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_EncryptedLocationEndorsementWithId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_EncryptedLocationEndorsementWithId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031LocationEndorsement.proto\022\nProj.Proto\032" +
      "\nData.proto\032\023LocationClaim.proto\"c\n\032Loca" +
      "tionEndorsementRequest\0220\n\rlocationClaim\030" +
      "\001 \001(\0132\031.Proj.Proto.LocationClaim\022\023\n\013requ" +
      "esterId\030\002 \001(\005\"Q\n#EncryptedLocationEndors" +
      "ementRequest\022\014\n\004data\030\001 \001(\014\022\034\n\024initializa" +
      "tionVector\030\002 \001(\014\"\235\001\n)EncryptedLocationEn" +
      "dorsementRequestWithId\022\\\n#encryptedLocat" +
      "ionEndorsementRequest\030\001 \001(\0132/.Proj.Proto" +
      ".EncryptedLocationEndorsementRequest\022\022\n\n" +
      "receiverId\030\002 \001(\005\"\211\001\n\023LocationEndorsement" +
      "\022\021\n\twitnessId\030\001 \001(\005\022\017\n\007claimId\030\002 \001(\005\022\020\n\010" +
      "proverId\030\003 \001(\005\022\020\n\010timestep\030\004 \001(\005\022*\n\nenti" +
      "tyData\030\005 \001(\0132\026.Proj.Proto.EntityData\"J\n\034" +
      "EncryptedLocationEndorsement\022\014\n\004data\030\001 \001" +
      "(\014\022\034\n\024initializationVector\030\002 \001(\014\"\210\001\n\"Enc" +
      "ryptedLocationEndorsementWithId\022N\n\034encry" +
      "ptedLocationEndorsement\030\001 \001(\0132(.Proj.Pro" +
      "to.EncryptedLocationEndorsement\022\022\n\nrecei" +
      "verId\030\002 \001(\005B\027\n\023proj_contract.protoP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proj_contract.proto.Data.getDescriptor(),
          proj_contract.proto.LocationClaimOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_LocationEndorsementRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_LocationEndorsementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationEndorsementRequest_descriptor,
        new java.lang.String[] { "LocationClaim", "RequesterId", });
    internal_static_Proj_Proto_EncryptedLocationEndorsementRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Proj_Proto_EncryptedLocationEndorsementRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_EncryptedLocationEndorsementRequest_descriptor,
        new java.lang.String[] { "Data", "InitializationVector", });
    internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_EncryptedLocationEndorsementRequestWithId_descriptor,
        new java.lang.String[] { "EncryptedLocationEndorsementRequest", "ReceiverId", });
    internal_static_Proj_Proto_LocationEndorsement_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Proj_Proto_LocationEndorsement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationEndorsement_descriptor,
        new java.lang.String[] { "WitnessId", "ClaimId", "ProverId", "Timestep", "EntityData", });
    internal_static_Proj_Proto_EncryptedLocationEndorsement_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Proj_Proto_EncryptedLocationEndorsement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_EncryptedLocationEndorsement_descriptor,
        new java.lang.String[] { "Data", "InitializationVector", });
    internal_static_Proj_Proto_EncryptedLocationEndorsementWithId_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Proj_Proto_EncryptedLocationEndorsementWithId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_EncryptedLocationEndorsementWithId_descriptor,
        new java.lang.String[] { "EncryptedLocationEndorsement", "ReceiverId", });
    proj_contract.proto.Data.getDescriptor();
    proj_contract.proto.LocationClaimOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
