// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationClaim.proto

package proj_contract.proto;

/**
 * Protobuf type {@code Proj.Proto.LocationClaimWithId}
 */
public  final class LocationClaimWithId extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Proj.Proto.LocationClaimWithId)
    LocationClaimWithIdOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocationClaimWithId.newBuilder() to construct.
  private LocationClaimWithId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocationClaimWithId() {
    receiverId_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocationClaimWithId(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            proj_contract.proto.LocationClaim.Builder subBuilder = null;
            if (locationClaim_ != null) {
              subBuilder = locationClaim_.toBuilder();
            }
            locationClaim_ = input.readMessage(proj_contract.proto.LocationClaim.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(locationClaim_);
              locationClaim_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {

            receiverId_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_LocationClaimWithId_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_LocationClaimWithId_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            proj_contract.proto.LocationClaimWithId.class, proj_contract.proto.LocationClaimWithId.Builder.class);
  }

  public static final int LOCATIONCLAIM_FIELD_NUMBER = 1;
  private proj_contract.proto.LocationClaim locationClaim_;
  /**
   * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
   */
  public boolean hasLocationClaim() {
    return locationClaim_ != null;
  }
  /**
   * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
   */
  public proj_contract.proto.LocationClaim getLocationClaim() {
    return locationClaim_ == null ? proj_contract.proto.LocationClaim.getDefaultInstance() : locationClaim_;
  }
  /**
   * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
   */
  public proj_contract.proto.LocationClaimOrBuilder getLocationClaimOrBuilder() {
    return getLocationClaim();
  }

  public static final int RECEIVERID_FIELD_NUMBER = 2;
  private int receiverId_;
  /**
   * <code>int32 receiverId = 2;</code>
   */
  public int getReceiverId() {
    return receiverId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (locationClaim_ != null) {
      output.writeMessage(1, getLocationClaim());
    }
    if (receiverId_ != 0) {
      output.writeInt32(2, receiverId_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (locationClaim_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLocationClaim());
    }
    if (receiverId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, receiverId_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof proj_contract.proto.LocationClaimWithId)) {
      return super.equals(obj);
    }
    proj_contract.proto.LocationClaimWithId other = (proj_contract.proto.LocationClaimWithId) obj;

    boolean result = true;
    result = result && (hasLocationClaim() == other.hasLocationClaim());
    if (hasLocationClaim()) {
      result = result && getLocationClaim()
          .equals(other.getLocationClaim());
    }
    result = result && (getReceiverId()
        == other.getReceiverId());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLocationClaim()) {
      hash = (37 * hash) + LOCATIONCLAIM_FIELD_NUMBER;
      hash = (53 * hash) + getLocationClaim().hashCode();
    }
    hash = (37 * hash) + RECEIVERID_FIELD_NUMBER;
    hash = (53 * hash) + getReceiverId();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static proj_contract.proto.LocationClaimWithId parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.LocationClaimWithId parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.LocationClaimWithId parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.LocationClaimWithId parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.LocationClaimWithId parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static proj_contract.proto.LocationClaimWithId parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static proj_contract.proto.LocationClaimWithId parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proj_contract.proto.LocationClaimWithId parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static proj_contract.proto.LocationClaimWithId parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static proj_contract.proto.LocationClaimWithId parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static proj_contract.proto.LocationClaimWithId parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static proj_contract.proto.LocationClaimWithId parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(proj_contract.proto.LocationClaimWithId prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Proj.Proto.LocationClaimWithId}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Proj.Proto.LocationClaimWithId)
      proj_contract.proto.LocationClaimWithIdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_LocationClaimWithId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_LocationClaimWithId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proj_contract.proto.LocationClaimWithId.class, proj_contract.proto.LocationClaimWithId.Builder.class);
    }

    // Construct using proj_contract.proto.LocationClaimWithId.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (locationClaimBuilder_ == null) {
        locationClaim_ = null;
      } else {
        locationClaim_ = null;
        locationClaimBuilder_ = null;
      }
      receiverId_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return proj_contract.proto.LocationClaimOuterClass.internal_static_Proj_Proto_LocationClaimWithId_descriptor;
    }

    @java.lang.Override
    public proj_contract.proto.LocationClaimWithId getDefaultInstanceForType() {
      return proj_contract.proto.LocationClaimWithId.getDefaultInstance();
    }

    @java.lang.Override
    public proj_contract.proto.LocationClaimWithId build() {
      proj_contract.proto.LocationClaimWithId result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public proj_contract.proto.LocationClaimWithId buildPartial() {
      proj_contract.proto.LocationClaimWithId result = new proj_contract.proto.LocationClaimWithId(this);
      if (locationClaimBuilder_ == null) {
        result.locationClaim_ = locationClaim_;
      } else {
        result.locationClaim_ = locationClaimBuilder_.build();
      }
      result.receiverId_ = receiverId_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof proj_contract.proto.LocationClaimWithId) {
        return mergeFrom((proj_contract.proto.LocationClaimWithId)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(proj_contract.proto.LocationClaimWithId other) {
      if (other == proj_contract.proto.LocationClaimWithId.getDefaultInstance()) return this;
      if (other.hasLocationClaim()) {
        mergeLocationClaim(other.getLocationClaim());
      }
      if (other.getReceiverId() != 0) {
        setReceiverId(other.getReceiverId());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      proj_contract.proto.LocationClaimWithId parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (proj_contract.proto.LocationClaimWithId) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private proj_contract.proto.LocationClaim locationClaim_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        proj_contract.proto.LocationClaim, proj_contract.proto.LocationClaim.Builder, proj_contract.proto.LocationClaimOrBuilder> locationClaimBuilder_;
    /**
     * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
     */
    public boolean hasLocationClaim() {
      return locationClaimBuilder_ != null || locationClaim_ != null;
    }
    /**
     * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
     */
    public proj_contract.proto.LocationClaim getLocationClaim() {
      if (locationClaimBuilder_ == null) {
        return locationClaim_ == null ? proj_contract.proto.LocationClaim.getDefaultInstance() : locationClaim_;
      } else {
        return locationClaimBuilder_.getMessage();
      }
    }
    /**
     * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
     */
    public Builder setLocationClaim(proj_contract.proto.LocationClaim value) {
      if (locationClaimBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        locationClaim_ = value;
        onChanged();
      } else {
        locationClaimBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
     */
    public Builder setLocationClaim(
        proj_contract.proto.LocationClaim.Builder builderForValue) {
      if (locationClaimBuilder_ == null) {
        locationClaim_ = builderForValue.build();
        onChanged();
      } else {
        locationClaimBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
     */
    public Builder mergeLocationClaim(proj_contract.proto.LocationClaim value) {
      if (locationClaimBuilder_ == null) {
        if (locationClaim_ != null) {
          locationClaim_ =
            proj_contract.proto.LocationClaim.newBuilder(locationClaim_).mergeFrom(value).buildPartial();
        } else {
          locationClaim_ = value;
        }
        onChanged();
      } else {
        locationClaimBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
     */
    public Builder clearLocationClaim() {
      if (locationClaimBuilder_ == null) {
        locationClaim_ = null;
        onChanged();
      } else {
        locationClaim_ = null;
        locationClaimBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
     */
    public proj_contract.proto.LocationClaim.Builder getLocationClaimBuilder() {
      
      onChanged();
      return getLocationClaimFieldBuilder().getBuilder();
    }
    /**
     * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
     */
    public proj_contract.proto.LocationClaimOrBuilder getLocationClaimOrBuilder() {
      if (locationClaimBuilder_ != null) {
        return locationClaimBuilder_.getMessageOrBuilder();
      } else {
        return locationClaim_ == null ?
            proj_contract.proto.LocationClaim.getDefaultInstance() : locationClaim_;
      }
    }
    /**
     * <code>.Proj.Proto.LocationClaim locationClaim = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        proj_contract.proto.LocationClaim, proj_contract.proto.LocationClaim.Builder, proj_contract.proto.LocationClaimOrBuilder> 
        getLocationClaimFieldBuilder() {
      if (locationClaimBuilder_ == null) {
        locationClaimBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            proj_contract.proto.LocationClaim, proj_contract.proto.LocationClaim.Builder, proj_contract.proto.LocationClaimOrBuilder>(
                getLocationClaim(),
                getParentForChildren(),
                isClean());
        locationClaim_ = null;
      }
      return locationClaimBuilder_;
    }

    private int receiverId_ ;
    /**
     * <code>int32 receiverId = 2;</code>
     */
    public int getReceiverId() {
      return receiverId_;
    }
    /**
     * <code>int32 receiverId = 2;</code>
     */
    public Builder setReceiverId(int value) {
      
      receiverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 receiverId = 2;</code>
     */
    public Builder clearReceiverId() {
      
      receiverId_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Proj.Proto.LocationClaimWithId)
  }

  // @@protoc_insertion_point(class_scope:Proj.Proto.LocationClaimWithId)
  private static final proj_contract.proto.LocationClaimWithId DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new proj_contract.proto.LocationClaimWithId();
  }

  public static proj_contract.proto.LocationClaimWithId getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocationClaimWithId>
      PARSER = new com.google.protobuf.AbstractParser<LocationClaimWithId>() {
    @java.lang.Override
    public LocationClaimWithId parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocationClaimWithId(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocationClaimWithId> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocationClaimWithId> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public proj_contract.proto.LocationClaimWithId getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

