// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Observation.proto

package proj_contract.proto;

public interface ObservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.Observation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
