// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Data.proto

package proj_contract.proto;

public interface TimestepDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.TimestepData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Proj.Proto.Coordinates coordinates = 1;</code>
   */
  boolean hasCoordinates();
  /**
   * <code>.Proj.Proto.Coordinates coordinates = 1;</code>
   */
  proj_contract.proto.Coordinates getCoordinates();
  /**
   * <code>.Proj.Proto.Coordinates coordinates = 1;</code>
   */
  proj_contract.proto.CoordinatesOrBuilder getCoordinatesOrBuilder();

  /**
   * <code>int32 timestep = 2;</code>
   */
  int getTimestep();
}
