// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationClaim.proto

package Proj.Proto;

/**
 * <pre>
 * definition of the location claim
 * </pre>
 *
 * Protobuf type {@code Proj.Proto.LocationClaim}
 */
public  final class LocationClaim extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Proj.Proto.LocationClaim)
    LocationClaimOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocationClaim.newBuilder() to construct.
  private LocationClaim(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocationClaim() {
    claimId_ = "";
    proverId_ = "";
    time_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocationClaim(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            claimId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            proverId_ = s;
            break;
          }
          case 26: {
            Proj.Proto.Location.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(Proj.Proto.Location.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
          case 32: {

            time_ = input.readInt32();
            break;
          }
          case 42: {
            Proj.Proto.Observation.Builder subBuilder = null;
            if (observation_ != null) {
              subBuilder = observation_.toBuilder();
            }
            observation_ = input.readMessage(Proj.Proto.Observation.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(observation_);
              observation_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Proj.Proto.LocationClaimProto.internal_static_Proj_Proto_LocationClaim_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Proj.Proto.LocationClaimProto.internal_static_Proj_Proto_LocationClaim_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Proj.Proto.LocationClaim.class, Proj.Proto.LocationClaim.Builder.class);
  }

  public static final int CLAIMID_FIELD_NUMBER = 1;
  private volatile java.lang.Object claimId_;
  /**
   * <code>string claimId = 1;</code>
   */
  public java.lang.String getClaimId() {
    java.lang.Object ref = claimId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      claimId_ = s;
      return s;
    }
  }
  /**
   * <code>string claimId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClaimIdBytes() {
    java.lang.Object ref = claimId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      claimId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROVERID_FIELD_NUMBER = 2;
  private volatile java.lang.Object proverId_;
  /**
   * <code>string proverId = 2;</code>
   */
  public java.lang.String getProverId() {
    java.lang.Object ref = proverId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      proverId_ = s;
      return s;
    }
  }
  /**
   * <code>string proverId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProverIdBytes() {
    java.lang.Object ref = proverId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      proverId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOCATION_FIELD_NUMBER = 3;
  private Proj.Proto.Location location_;
  /**
   * <code>.Proj.Proto.Location location = 3;</code>
   */
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.Proj.Proto.Location location = 3;</code>
   */
  public Proj.Proto.Location getLocation() {
    return location_ == null ? Proj.Proto.Location.getDefaultInstance() : location_;
  }
  /**
   * <code>.Proj.Proto.Location location = 3;</code>
   */
  public Proj.Proto.LocationOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  public static final int TIME_FIELD_NUMBER = 4;
  private int time_;
  /**
   * <code>int32 time = 4;</code>
   */
  public int getTime() {
    return time_;
  }

  public static final int OBSERVATION_FIELD_NUMBER = 5;
  private Proj.Proto.Observation observation_;
  /**
   * <code>.Proj.Proto.Observation observation = 5;</code>
   */
  public boolean hasObservation() {
    return observation_ != null;
  }
  /**
   * <code>.Proj.Proto.Observation observation = 5;</code>
   */
  public Proj.Proto.Observation getObservation() {
    return observation_ == null ? Proj.Proto.Observation.getDefaultInstance() : observation_;
  }
  /**
   * <code>.Proj.Proto.Observation observation = 5;</code>
   */
  public Proj.Proto.ObservationOrBuilder getObservationOrBuilder() {
    return getObservation();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClaimIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, claimId_);
    }
    if (!getProverIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, proverId_);
    }
    if (location_ != null) {
      output.writeMessage(3, getLocation());
    }
    if (time_ != 0) {
      output.writeInt32(4, time_);
    }
    if (observation_ != null) {
      output.writeMessage(5, getObservation());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClaimIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, claimId_);
    }
    if (!getProverIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, proverId_);
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getLocation());
    }
    if (time_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, time_);
    }
    if (observation_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getObservation());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Proj.Proto.LocationClaim)) {
      return super.equals(obj);
    }
    Proj.Proto.LocationClaim other = (Proj.Proto.LocationClaim) obj;

    boolean result = true;
    result = result && getClaimId()
        .equals(other.getClaimId());
    result = result && getProverId()
        .equals(other.getProverId());
    result = result && (hasLocation() == other.hasLocation());
    if (hasLocation()) {
      result = result && getLocation()
          .equals(other.getLocation());
    }
    result = result && (getTime()
        == other.getTime());
    result = result && (hasObservation() == other.hasObservation());
    if (hasObservation()) {
      result = result && getObservation()
          .equals(other.getObservation());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLAIMID_FIELD_NUMBER;
    hash = (53 * hash) + getClaimId().hashCode();
    hash = (37 * hash) + PROVERID_FIELD_NUMBER;
    hash = (53 * hash) + getProverId().hashCode();
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    hash = (37 * hash) + TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTime();
    if (hasObservation()) {
      hash = (37 * hash) + OBSERVATION_FIELD_NUMBER;
      hash = (53 * hash) + getObservation().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Proj.Proto.LocationClaim parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Proj.Proto.LocationClaim parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Proj.Proto.LocationClaim parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Proj.Proto.LocationClaim parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Proj.Proto.LocationClaim parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Proj.Proto.LocationClaim parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Proj.Proto.LocationClaim parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Proj.Proto.LocationClaim parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Proj.Proto.LocationClaim parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Proj.Proto.LocationClaim parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Proj.Proto.LocationClaim parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Proj.Proto.LocationClaim parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Proj.Proto.LocationClaim prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * definition of the location claim
   * </pre>
   *
   * Protobuf type {@code Proj.Proto.LocationClaim}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Proj.Proto.LocationClaim)
      Proj.Proto.LocationClaimOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Proj.Proto.LocationClaimProto.internal_static_Proj_Proto_LocationClaim_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Proj.Proto.LocationClaimProto.internal_static_Proj_Proto_LocationClaim_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Proj.Proto.LocationClaim.class, Proj.Proto.LocationClaim.Builder.class);
    }

    // Construct using Proj.Proto.LocationClaim.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      claimId_ = "";

      proverId_ = "";

      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      time_ = 0;

      if (observationBuilder_ == null) {
        observation_ = null;
      } else {
        observation_ = null;
        observationBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Proj.Proto.LocationClaimProto.internal_static_Proj_Proto_LocationClaim_descriptor;
    }

    @java.lang.Override
    public Proj.Proto.LocationClaim getDefaultInstanceForType() {
      return Proj.Proto.LocationClaim.getDefaultInstance();
    }

    @java.lang.Override
    public Proj.Proto.LocationClaim build() {
      Proj.Proto.LocationClaim result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Proj.Proto.LocationClaim buildPartial() {
      Proj.Proto.LocationClaim result = new Proj.Proto.LocationClaim(this);
      result.claimId_ = claimId_;
      result.proverId_ = proverId_;
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      result.time_ = time_;
      if (observationBuilder_ == null) {
        result.observation_ = observation_;
      } else {
        result.observation_ = observationBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Proj.Proto.LocationClaim) {
        return mergeFrom((Proj.Proto.LocationClaim)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Proj.Proto.LocationClaim other) {
      if (other == Proj.Proto.LocationClaim.getDefaultInstance()) return this;
      if (!other.getClaimId().isEmpty()) {
        claimId_ = other.claimId_;
        onChanged();
      }
      if (!other.getProverId().isEmpty()) {
        proverId_ = other.proverId_;
        onChanged();
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (other.getTime() != 0) {
        setTime(other.getTime());
      }
      if (other.hasObservation()) {
        mergeObservation(other.getObservation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Proj.Proto.LocationClaim parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Proj.Proto.LocationClaim) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object claimId_ = "";
    /**
     * <code>string claimId = 1;</code>
     */
    public java.lang.String getClaimId() {
      java.lang.Object ref = claimId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        claimId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string claimId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClaimIdBytes() {
      java.lang.Object ref = claimId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        claimId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string claimId = 1;</code>
     */
    public Builder setClaimId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      claimId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string claimId = 1;</code>
     */
    public Builder clearClaimId() {
      
      claimId_ = getDefaultInstance().getClaimId();
      onChanged();
      return this;
    }
    /**
     * <code>string claimId = 1;</code>
     */
    public Builder setClaimIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      claimId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object proverId_ = "";
    /**
     * <code>string proverId = 2;</code>
     */
    public java.lang.String getProverId() {
      java.lang.Object ref = proverId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proverId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string proverId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProverIdBytes() {
      java.lang.Object ref = proverId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proverId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string proverId = 2;</code>
     */
    public Builder setProverId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      proverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string proverId = 2;</code>
     */
    public Builder clearProverId() {
      
      proverId_ = getDefaultInstance().getProverId();
      onChanged();
      return this;
    }
    /**
     * <code>string proverId = 2;</code>
     */
    public Builder setProverIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      proverId_ = value;
      onChanged();
      return this;
    }

    private Proj.Proto.Location location_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Proj.Proto.Location, Proj.Proto.Location.Builder, Proj.Proto.LocationOrBuilder> locationBuilder_;
    /**
     * <code>.Proj.Proto.Location location = 3;</code>
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <code>.Proj.Proto.Location location = 3;</code>
     */
    public Proj.Proto.Location getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? Proj.Proto.Location.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>.Proj.Proto.Location location = 3;</code>
     */
    public Builder setLocation(Proj.Proto.Location value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Location location = 3;</code>
     */
    public Builder setLocation(
        Proj.Proto.Location.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Location location = 3;</code>
     */
    public Builder mergeLocation(Proj.Proto.Location value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            Proj.Proto.Location.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Location location = 3;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Location location = 3;</code>
     */
    public Proj.Proto.Location.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Proj.Proto.Location location = 3;</code>
     */
    public Proj.Proto.LocationOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            Proj.Proto.Location.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>.Proj.Proto.Location location = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Proj.Proto.Location, Proj.Proto.Location.Builder, Proj.Proto.LocationOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Proj.Proto.Location, Proj.Proto.Location.Builder, Proj.Proto.LocationOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private int time_ ;
    /**
     * <code>int32 time = 4;</code>
     */
    public int getTime() {
      return time_;
    }
    /**
     * <code>int32 time = 4;</code>
     */
    public Builder setTime(int value) {
      
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 time = 4;</code>
     */
    public Builder clearTime() {
      
      time_ = 0;
      onChanged();
      return this;
    }

    private Proj.Proto.Observation observation_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Proj.Proto.Observation, Proj.Proto.Observation.Builder, Proj.Proto.ObservationOrBuilder> observationBuilder_;
    /**
     * <code>.Proj.Proto.Observation observation = 5;</code>
     */
    public boolean hasObservation() {
      return observationBuilder_ != null || observation_ != null;
    }
    /**
     * <code>.Proj.Proto.Observation observation = 5;</code>
     */
    public Proj.Proto.Observation getObservation() {
      if (observationBuilder_ == null) {
        return observation_ == null ? Proj.Proto.Observation.getDefaultInstance() : observation_;
      } else {
        return observationBuilder_.getMessage();
      }
    }
    /**
     * <code>.Proj.Proto.Observation observation = 5;</code>
     */
    public Builder setObservation(Proj.Proto.Observation value) {
      if (observationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        observation_ = value;
        onChanged();
      } else {
        observationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Observation observation = 5;</code>
     */
    public Builder setObservation(
        Proj.Proto.Observation.Builder builderForValue) {
      if (observationBuilder_ == null) {
        observation_ = builderForValue.build();
        onChanged();
      } else {
        observationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Observation observation = 5;</code>
     */
    public Builder mergeObservation(Proj.Proto.Observation value) {
      if (observationBuilder_ == null) {
        if (observation_ != null) {
          observation_ =
            Proj.Proto.Observation.newBuilder(observation_).mergeFrom(value).buildPartial();
        } else {
          observation_ = value;
        }
        onChanged();
      } else {
        observationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Observation observation = 5;</code>
     */
    public Builder clearObservation() {
      if (observationBuilder_ == null) {
        observation_ = null;
        onChanged();
      } else {
        observation_ = null;
        observationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Observation observation = 5;</code>
     */
    public Proj.Proto.Observation.Builder getObservationBuilder() {
      
      onChanged();
      return getObservationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Proj.Proto.Observation observation = 5;</code>
     */
    public Proj.Proto.ObservationOrBuilder getObservationOrBuilder() {
      if (observationBuilder_ != null) {
        return observationBuilder_.getMessageOrBuilder();
      } else {
        return observation_ == null ?
            Proj.Proto.Observation.getDefaultInstance() : observation_;
      }
    }
    /**
     * <code>.Proj.Proto.Observation observation = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Proj.Proto.Observation, Proj.Proto.Observation.Builder, Proj.Proto.ObservationOrBuilder> 
        getObservationFieldBuilder() {
      if (observationBuilder_ == null) {
        observationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Proj.Proto.Observation, Proj.Proto.Observation.Builder, Proj.Proto.ObservationOrBuilder>(
                getObservation(),
                getParentForChildren(),
                isClean());
        observation_ = null;
      }
      return observationBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Proj.Proto.LocationClaim)
  }

  // @@protoc_insertion_point(class_scope:Proj.Proto.LocationClaim)
  private static final Proj.Proto.LocationClaim DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Proj.Proto.LocationClaim();
  }

  public static Proj.Proto.LocationClaim getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocationClaim>
      PARSER = new com.google.protobuf.AbstractParser<LocationClaim>() {
    @java.lang.Override
    public LocationClaim parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocationClaim(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocationClaim> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocationClaim> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Proj.Proto.LocationClaim getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

