// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Location.proto

package Proj.Proto;

public interface LocationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.Location)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 x = 1;</code>
   */
  int getX();

  /**
   * <code>int32 y = 2;</code>
   */
  int getY();
}
