// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LocationClaim.proto

package Proj.Proto;

public interface LocationClaimOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.LocationClaim)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string claimId = 1;</code>
   */
  java.lang.String getClaimId();
  /**
   * <code>string claimId = 1;</code>
   */
  com.google.protobuf.ByteString
      getClaimIdBytes();

  /**
   * <code>string proverId = 2;</code>
   */
  java.lang.String getProverId();
  /**
   * <code>string proverId = 2;</code>
   */
  com.google.protobuf.ByteString
      getProverIdBytes();

  /**
   * <code>.Proj.Proto.Location location = 3;</code>
   */
  boolean hasLocation();
  /**
   * <code>.Proj.Proto.Location location = 3;</code>
   */
  Proj.Proto.Location getLocation();
  /**
   * <code>.Proj.Proto.Location location = 3;</code>
   */
  Proj.Proto.LocationOrBuilder getLocationOrBuilder();

  /**
   * <code>int32 time = 4;</code>
   */
  int getTime();

  /**
   * <code>.Proj.Proto.Observation observation = 5;</code>
   */
  boolean hasObservation();
  /**
   * <code>.Proj.Proto.Observation observation = 5;</code>
   */
  Proj.Proto.Observation getObservation();
  /**
   * <code>.Proj.Proto.Observation observation = 5;</code>
   */
  Proj.Proto.ObservationOrBuilder getObservationOrBuilder();
}
