// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_endorse.proto

package Proj.Proto;

public final class LocEndorseProto {
  private LocEndorseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationEndorsement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationEndorsement_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_SignedLocationEndorsement_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_SignedLocationEndorsement_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021loc_endorse.proto\022\nProj.Proto\032\031google/" +
      "protobuf/any.proto\032\016loc_time.proto\032\017sign" +
      "ature.proto\"\227\001\n\023LocationEndorsement\022\021\n\tw" +
      "itnessId\030\001 \001(\t\022\017\n\007claimId\030\002 \001(\t\022\036\n\004time\030" +
      "\003 \001(\0132\020.Proj.Proto.Time\022\024\n\014evidenceType\030" +
      "\004 \001(\t\022&\n\010evidence\030\005 \001(\0132\024.google.protobu" +
      "f.Any\"\202\001\n\031SignedLocationEndorsement\0224\n\013e" +
      "ndorsement\030\001 \001(\0132\037.Proj.Proto.LocationEn" +
      "dorsement\022/\n\020witnessSignature\030\002 \001(\0132\025.Pr" +
      "oj.Proto.SignatureB\037\n\nProj.ProtoB\017LocEnd" +
      "orseProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          Proj.Proto.LocTimeProto.getDescriptor(),
          Proj.Proto.SignatureProto.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_LocationEndorsement_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_LocationEndorsement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationEndorsement_descriptor,
        new java.lang.String[] { "WitnessId", "ClaimId", "Time", "EvidenceType", "Evidence", });
    internal_static_Proj_Proto_SignedLocationEndorsement_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Proj_Proto_SignedLocationEndorsement_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_SignedLocationEndorsement_descriptor,
        new java.lang.String[] { "Endorsement", "WitnessSignature", });
    com.google.protobuf.AnyProto.getDescriptor();
    Proj.Proto.LocTimeProto.getDescriptor();
    Proj.Proto.SignatureProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
