// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CollectedData.proto

package Proj.Proto;

public interface EntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.Entity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 x = 2;</code>
   */
  int getX();

  /**
   * <code>int32 y = 3;</code>
   */
  int getY();

  /**
   * <code>string id = 4;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 4;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
