// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_cert.proto

package Proj.Proto;

/**
 * <pre>
 * A location certificate is a verified location claim, optionally supported by endorsements
 * </pre>
 *
 * Protobuf type {@code Proj.Proto.LocationCertificate}
 */
public  final class LocationCertificate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Proj.Proto.LocationCertificate)
    LocationCertificateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LocationCertificate.newBuilder() to construct.
  private LocationCertificate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LocationCertificate() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LocationCertificate(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            Proj.Proto.LocationVerification.Builder subBuilder = null;
            if (verification_ != null) {
              subBuilder = verification_.toBuilder();
            }
            verification_ = input.readMessage(Proj.Proto.LocationVerification.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(verification_);
              verification_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            Proj.Proto.Signature.Builder subBuilder = null;
            if (verifierSignature_ != null) {
              subBuilder = verifierSignature_.toBuilder();
            }
            verifierSignature_ = input.readMessage(Proj.Proto.Signature.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(verifierSignature_);
              verifierSignature_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Proj.Proto.LocCertProto.internal_static_Proj_Proto_LocationCertificate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Proj.Proto.LocCertProto.internal_static_Proj_Proto_LocationCertificate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Proj.Proto.LocationCertificate.class, Proj.Proto.LocationCertificate.Builder.class);
  }

  public static final int VERIFICATION_FIELD_NUMBER = 1;
  private Proj.Proto.LocationVerification verification_;
  /**
   * <code>.Proj.Proto.LocationVerification verification = 1;</code>
   */
  public boolean hasVerification() {
    return verification_ != null;
  }
  /**
   * <code>.Proj.Proto.LocationVerification verification = 1;</code>
   */
  public Proj.Proto.LocationVerification getVerification() {
    return verification_ == null ? Proj.Proto.LocationVerification.getDefaultInstance() : verification_;
  }
  /**
   * <code>.Proj.Proto.LocationVerification verification = 1;</code>
   */
  public Proj.Proto.LocationVerificationOrBuilder getVerificationOrBuilder() {
    return getVerification();
  }

  public static final int VERIFIERSIGNATURE_FIELD_NUMBER = 2;
  private Proj.Proto.Signature verifierSignature_;
  /**
   * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
   */
  public boolean hasVerifierSignature() {
    return verifierSignature_ != null;
  }
  /**
   * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
   */
  public Proj.Proto.Signature getVerifierSignature() {
    return verifierSignature_ == null ? Proj.Proto.Signature.getDefaultInstance() : verifierSignature_;
  }
  /**
   * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
   */
  public Proj.Proto.SignatureOrBuilder getVerifierSignatureOrBuilder() {
    return getVerifierSignature();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (verification_ != null) {
      output.writeMessage(1, getVerification());
    }
    if (verifierSignature_ != null) {
      output.writeMessage(2, getVerifierSignature());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (verification_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getVerification());
    }
    if (verifierSignature_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getVerifierSignature());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Proj.Proto.LocationCertificate)) {
      return super.equals(obj);
    }
    Proj.Proto.LocationCertificate other = (Proj.Proto.LocationCertificate) obj;

    boolean result = true;
    result = result && (hasVerification() == other.hasVerification());
    if (hasVerification()) {
      result = result && getVerification()
          .equals(other.getVerification());
    }
    result = result && (hasVerifierSignature() == other.hasVerifierSignature());
    if (hasVerifierSignature()) {
      result = result && getVerifierSignature()
          .equals(other.getVerifierSignature());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasVerification()) {
      hash = (37 * hash) + VERIFICATION_FIELD_NUMBER;
      hash = (53 * hash) + getVerification().hashCode();
    }
    if (hasVerifierSignature()) {
      hash = (37 * hash) + VERIFIERSIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getVerifierSignature().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Proj.Proto.LocationCertificate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Proj.Proto.LocationCertificate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Proj.Proto.LocationCertificate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Proj.Proto.LocationCertificate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Proj.Proto.LocationCertificate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Proj.Proto.LocationCertificate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Proj.Proto.LocationCertificate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Proj.Proto.LocationCertificate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Proj.Proto.LocationCertificate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Proj.Proto.LocationCertificate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Proj.Proto.LocationCertificate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Proj.Proto.LocationCertificate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Proj.Proto.LocationCertificate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A location certificate is a verified location claim, optionally supported by endorsements
   * </pre>
   *
   * Protobuf type {@code Proj.Proto.LocationCertificate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Proj.Proto.LocationCertificate)
      Proj.Proto.LocationCertificateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Proj.Proto.LocCertProto.internal_static_Proj_Proto_LocationCertificate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Proj.Proto.LocCertProto.internal_static_Proj_Proto_LocationCertificate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Proj.Proto.LocationCertificate.class, Proj.Proto.LocationCertificate.Builder.class);
    }

    // Construct using Proj.Proto.LocationCertificate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (verificationBuilder_ == null) {
        verification_ = null;
      } else {
        verification_ = null;
        verificationBuilder_ = null;
      }
      if (verifierSignatureBuilder_ == null) {
        verifierSignature_ = null;
      } else {
        verifierSignature_ = null;
        verifierSignatureBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Proj.Proto.LocCertProto.internal_static_Proj_Proto_LocationCertificate_descriptor;
    }

    @java.lang.Override
    public Proj.Proto.LocationCertificate getDefaultInstanceForType() {
      return Proj.Proto.LocationCertificate.getDefaultInstance();
    }

    @java.lang.Override
    public Proj.Proto.LocationCertificate build() {
      Proj.Proto.LocationCertificate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Proj.Proto.LocationCertificate buildPartial() {
      Proj.Proto.LocationCertificate result = new Proj.Proto.LocationCertificate(this);
      if (verificationBuilder_ == null) {
        result.verification_ = verification_;
      } else {
        result.verification_ = verificationBuilder_.build();
      }
      if (verifierSignatureBuilder_ == null) {
        result.verifierSignature_ = verifierSignature_;
      } else {
        result.verifierSignature_ = verifierSignatureBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Proj.Proto.LocationCertificate) {
        return mergeFrom((Proj.Proto.LocationCertificate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Proj.Proto.LocationCertificate other) {
      if (other == Proj.Proto.LocationCertificate.getDefaultInstance()) return this;
      if (other.hasVerification()) {
        mergeVerification(other.getVerification());
      }
      if (other.hasVerifierSignature()) {
        mergeVerifierSignature(other.getVerifierSignature());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Proj.Proto.LocationCertificate parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Proj.Proto.LocationCertificate) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Proj.Proto.LocationVerification verification_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Proj.Proto.LocationVerification, Proj.Proto.LocationVerification.Builder, Proj.Proto.LocationVerificationOrBuilder> verificationBuilder_;
    /**
     * <code>.Proj.Proto.LocationVerification verification = 1;</code>
     */
    public boolean hasVerification() {
      return verificationBuilder_ != null || verification_ != null;
    }
    /**
     * <code>.Proj.Proto.LocationVerification verification = 1;</code>
     */
    public Proj.Proto.LocationVerification getVerification() {
      if (verificationBuilder_ == null) {
        return verification_ == null ? Proj.Proto.LocationVerification.getDefaultInstance() : verification_;
      } else {
        return verificationBuilder_.getMessage();
      }
    }
    /**
     * <code>.Proj.Proto.LocationVerification verification = 1;</code>
     */
    public Builder setVerification(Proj.Proto.LocationVerification value) {
      if (verificationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        verification_ = value;
        onChanged();
      } else {
        verificationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.LocationVerification verification = 1;</code>
     */
    public Builder setVerification(
        Proj.Proto.LocationVerification.Builder builderForValue) {
      if (verificationBuilder_ == null) {
        verification_ = builderForValue.build();
        onChanged();
      } else {
        verificationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.LocationVerification verification = 1;</code>
     */
    public Builder mergeVerification(Proj.Proto.LocationVerification value) {
      if (verificationBuilder_ == null) {
        if (verification_ != null) {
          verification_ =
            Proj.Proto.LocationVerification.newBuilder(verification_).mergeFrom(value).buildPartial();
        } else {
          verification_ = value;
        }
        onChanged();
      } else {
        verificationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.LocationVerification verification = 1;</code>
     */
    public Builder clearVerification() {
      if (verificationBuilder_ == null) {
        verification_ = null;
        onChanged();
      } else {
        verification_ = null;
        verificationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.LocationVerification verification = 1;</code>
     */
    public Proj.Proto.LocationVerification.Builder getVerificationBuilder() {
      
      onChanged();
      return getVerificationFieldBuilder().getBuilder();
    }
    /**
     * <code>.Proj.Proto.LocationVerification verification = 1;</code>
     */
    public Proj.Proto.LocationVerificationOrBuilder getVerificationOrBuilder() {
      if (verificationBuilder_ != null) {
        return verificationBuilder_.getMessageOrBuilder();
      } else {
        return verification_ == null ?
            Proj.Proto.LocationVerification.getDefaultInstance() : verification_;
      }
    }
    /**
     * <code>.Proj.Proto.LocationVerification verification = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Proj.Proto.LocationVerification, Proj.Proto.LocationVerification.Builder, Proj.Proto.LocationVerificationOrBuilder> 
        getVerificationFieldBuilder() {
      if (verificationBuilder_ == null) {
        verificationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Proj.Proto.LocationVerification, Proj.Proto.LocationVerification.Builder, Proj.Proto.LocationVerificationOrBuilder>(
                getVerification(),
                getParentForChildren(),
                isClean());
        verification_ = null;
      }
      return verificationBuilder_;
    }

    private Proj.Proto.Signature verifierSignature_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        Proj.Proto.Signature, Proj.Proto.Signature.Builder, Proj.Proto.SignatureOrBuilder> verifierSignatureBuilder_;
    /**
     * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
     */
    public boolean hasVerifierSignature() {
      return verifierSignatureBuilder_ != null || verifierSignature_ != null;
    }
    /**
     * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
     */
    public Proj.Proto.Signature getVerifierSignature() {
      if (verifierSignatureBuilder_ == null) {
        return verifierSignature_ == null ? Proj.Proto.Signature.getDefaultInstance() : verifierSignature_;
      } else {
        return verifierSignatureBuilder_.getMessage();
      }
    }
    /**
     * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
     */
    public Builder setVerifierSignature(Proj.Proto.Signature value) {
      if (verifierSignatureBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        verifierSignature_ = value;
        onChanged();
      } else {
        verifierSignatureBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
     */
    public Builder setVerifierSignature(
        Proj.Proto.Signature.Builder builderForValue) {
      if (verifierSignatureBuilder_ == null) {
        verifierSignature_ = builderForValue.build();
        onChanged();
      } else {
        verifierSignatureBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
     */
    public Builder mergeVerifierSignature(Proj.Proto.Signature value) {
      if (verifierSignatureBuilder_ == null) {
        if (verifierSignature_ != null) {
          verifierSignature_ =
            Proj.Proto.Signature.newBuilder(verifierSignature_).mergeFrom(value).buildPartial();
        } else {
          verifierSignature_ = value;
        }
        onChanged();
      } else {
        verifierSignatureBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
     */
    public Builder clearVerifierSignature() {
      if (verifierSignatureBuilder_ == null) {
        verifierSignature_ = null;
        onChanged();
      } else {
        verifierSignature_ = null;
        verifierSignatureBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
     */
    public Proj.Proto.Signature.Builder getVerifierSignatureBuilder() {
      
      onChanged();
      return getVerifierSignatureFieldBuilder().getBuilder();
    }
    /**
     * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
     */
    public Proj.Proto.SignatureOrBuilder getVerifierSignatureOrBuilder() {
      if (verifierSignatureBuilder_ != null) {
        return verifierSignatureBuilder_.getMessageOrBuilder();
      } else {
        return verifierSignature_ == null ?
            Proj.Proto.Signature.getDefaultInstance() : verifierSignature_;
      }
    }
    /**
     * <code>.Proj.Proto.Signature verifierSignature = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        Proj.Proto.Signature, Proj.Proto.Signature.Builder, Proj.Proto.SignatureOrBuilder> 
        getVerifierSignatureFieldBuilder() {
      if (verifierSignatureBuilder_ == null) {
        verifierSignatureBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            Proj.Proto.Signature, Proj.Proto.Signature.Builder, Proj.Proto.SignatureOrBuilder>(
                getVerifierSignature(),
                getParentForChildren(),
                isClean());
        verifierSignature_ = null;
      }
      return verifierSignatureBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Proj.Proto.LocationCertificate)
  }

  // @@protoc_insertion_point(class_scope:Proj.Proto.LocationCertificate)
  private static final Proj.Proto.LocationCertificate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Proj.Proto.LocationCertificate();
  }

  public static Proj.Proto.LocationCertificate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LocationCertificate>
      PARSER = new com.google.protobuf.AbstractParser<LocationCertificate>() {
    @java.lang.Override
    public LocationCertificate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LocationCertificate(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LocationCertificate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LocationCertificate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Proj.Proto.LocationCertificate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

