// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_endorse.proto

package Proj.Proto;

public interface LocationEndorsementOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.LocationEndorsement)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * witness unique id
   * </pre>
   *
   * <code>string witnessId = 1;</code>
   */
  java.lang.String getWitnessId();
  /**
   * <pre>
   * witness unique id
   * </pre>
   *
   * <code>string witnessId = 1;</code>
   */
  com.google.protobuf.ByteString
      getWitnessIdBytes();

  /**
   * <pre>
   * the original location claim of the prover
   * </pre>
   *
   * <code>string claimId = 2;</code>
   */
  java.lang.String getClaimId();
  /**
   * <pre>
   * the original location claim of the prover
   * </pre>
   *
   * <code>string claimId = 2;</code>
   */
  com.google.protobuf.ByteString
      getClaimIdBytes();

  /**
   * <pre>
   * time of location endorsement - in one of alternative time schemas
   * </pre>
   *
   * <code>.Proj.Proto.Time time = 3;</code>
   */
  boolean hasTime();
  /**
   * <pre>
   * time of location endorsement - in one of alternative time schemas
   * </pre>
   *
   * <code>.Proj.Proto.Time time = 3;</code>
   */
  Proj.Proto.Time getTime();
  /**
   * <pre>
   * time of location endorsement - in one of alternative time schemas
   * </pre>
   *
   * <code>.Proj.Proto.Time time = 3;</code>
   */
  Proj.Proto.TimeOrBuilder getTimeOrBuilder();

  /**
   * <pre>
   * type of the evidence
   * </pre>
   *
   * <code>string evidenceType = 4;</code>
   */
  java.lang.String getEvidenceType();
  /**
   * <pre>
   * type of the evidence
   * </pre>
   *
   * <code>string evidenceType = 4;</code>
   */
  com.google.protobuf.ByteString
      getEvidenceTypeBytes();

  /**
   * <pre>
   * endorsement evidence
   * </pre>
   *
   * <code>.google.protobuf.Any evidence = 5;</code>
   */
  boolean hasEvidence();
  /**
   * <pre>
   * endorsement evidence
   * </pre>
   *
   * <code>.google.protobuf.Any evidence = 5;</code>
   */
  com.google.protobuf.Any getEvidence();
  /**
   * <pre>
   * endorsement evidence
   * </pre>
   *
   * <code>.google.protobuf.Any evidence = 5;</code>
   */
  com.google.protobuf.AnyOrBuilder getEvidenceOrBuilder();
}
