// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_cert.proto

package Proj.Proto;

public final class LocCertProto {
  private LocCertProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationVerification_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationVerification_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_LocationCertificate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_LocationCertificate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016loc_cert.proto\022\nProj.Proto\032\031google/pro" +
      "tobuf/any.proto\032\016loc_time.proto\032\017signatu" +
      "re.proto\"\261\001\n\024LocationVerification\022\022\n\nver" +
      "ifierId\030\001 \001(\t\022\017\n\007claimId\030\002 \001(\t\022\026\n\016endors" +
      "ementIds\030\003 \003(\t\022\036\n\004time\030\004 \001(\0132\020.Proj.Prot" +
      "o.Time\022\024\n\014evidenceType\030\005 \001(\t\022&\n\010evidence" +
      "\030\006 \001(\0132\024.google.protobuf.Any\"\177\n\023Location" +
      "Certificate\0226\n\014verification\030\001 \001(\0132 .Proj" +
      ".Proto.LocationVerification\0220\n\021verifierS" +
      "ignature\030\002 \001(\0132\025.Proj.Proto.SignatureB\034\n" +
      "\nProj.ProtoB\014LocCertProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          Proj.Proto.LocTimeProto.getDescriptor(),
          Proj.Proto.SignatureProto.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_LocationVerification_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_LocationVerification_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationVerification_descriptor,
        new java.lang.String[] { "VerifierId", "ClaimId", "EndorsementIds", "Time", "EvidenceType", "Evidence", });
    internal_static_Proj_Proto_LocationCertificate_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Proj_Proto_LocationCertificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_LocationCertificate_descriptor,
        new java.lang.String[] { "Verification", "VerifierSignature", });
    com.google.protobuf.AnyProto.getDescriptor();
    Proj.Proto.LocTimeProto.getDescriptor();
    Proj.Proto.SignatureProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
