// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loc_time.proto

package Proj.Proto;

public final class LocTimeProto {
  private LocTimeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_Location_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_Location_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_PoI_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_PoI_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_PoIProximity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_PoIProximity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_OLC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_OLC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_Time_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_Time_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_TimeInterval_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_TimeInterval_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_EpochTime_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_EpochTime_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016loc_time.proto\022\nProj.Proto\032\033google/pro" +
      "tobuf/empty.proto\032\037google/protobuf/times" +
      "tamp.proto\032\014latlng.proto\032\024localized_text" +
      ".proto\"\261\001\n\010Location\022%\n\006latLng\030\001 \001(\0132\023.Pr" +
      "oj.Google.LatLngH\000\022\036\n\003poi\030\002 \001(\0132\017.Proj.P" +
      "roto.PoIH\000\0222\n\016proximityToPoI\030\003 \001(\0132\030.Pro" +
      "j.Proto.PoIProximityH\000\022\036\n\003olc\030\004 \001(\0132\017.Pr" +
      "oj.Proto.OLCH\000B\n\n\010location\"R\n\003PoI\022\n\n\002id\030" +
      "\001 \001(\t\022\014\n\004name\030\002 \001(\t\0221\n\rlocalizedName\030\003 \003" +
      "(\0132\032.Proj.Google.LocalizedText\"J\n\014PoIPro" +
      "ximity\022\r\n\005poiId\030\001 \001(\t\022\025\n\rdistanceValue\030\002" +
      " \001(\004\022\024\n\014distanceUnit\030\003 \001(\t\"q\n\003OLC\022\025\n\rsou" +
      "thLatitude\030\001 \001(\001\022\025\n\rwestLongitude\030\002 \001(\001\022" +
      "\025\n\rnorthLatitude\030\003 \001(\001\022\025\n\reastLongitude\030" +
      "\004 \001(\001\022\016\n\006length\030\005 \001(\005\"\310\001\n\004Time\022/\n\ttimest" +
      "amp\030\001 \001(\0132\032.google.protobuf.TimestampH\000\022" +
      ",\n\010interval\030\002 \001(\0132\030.Proj.Proto.TimeInter" +
      "valH\000\0220\n\017relativeToEpoch\030\003 \001(\0132\025.Proj.Pr" +
      "oto.EpochTimeH\000\022\'\n\005empty\030\004 \001(\0132\026.google." +
      "protobuf.EmptyH\000B\006\n\004time\"b\n\014TimeInterval" +
      "\022)\n\005begin\030\001 \001(\0132\032.google.protobuf.Timest" +
      "amp\022\'\n\003end\030\002 \001(\0132\032.google.protobuf.Times" +
      "tamp\"A\n\tEpochTime\022\017\n\007epochId\030\001 \001(\t\022\021\n\tti" +
      "meValue\030\002 \001(\003\022\020\n\010timeUnit\030\003 \001(\tB\034\n\nProj." +
      "ProtoB\014LocTimeProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
          Proj.Google.LatLngProto.getDescriptor(),
          Proj.Google.LocalizedTextProto.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_Location_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_Location_descriptor,
        new java.lang.String[] { "LatLng", "Poi", "ProximityToPoI", "Olc", "Location", });
    internal_static_Proj_Proto_PoI_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Proj_Proto_PoI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_PoI_descriptor,
        new java.lang.String[] { "Id", "Name", "LocalizedName", });
    internal_static_Proj_Proto_PoIProximity_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Proj_Proto_PoIProximity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_PoIProximity_descriptor,
        new java.lang.String[] { "PoiId", "DistanceValue", "DistanceUnit", });
    internal_static_Proj_Proto_OLC_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Proj_Proto_OLC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_OLC_descriptor,
        new java.lang.String[] { "SouthLatitude", "WestLongitude", "NorthLatitude", "EastLongitude", "Length", });
    internal_static_Proj_Proto_Time_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Proj_Proto_Time_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_Time_descriptor,
        new java.lang.String[] { "Timestamp", "Interval", "RelativeToEpoch", "Empty", "Time", });
    internal_static_Proj_Proto_TimeInterval_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Proj_Proto_TimeInterval_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_TimeInterval_descriptor,
        new java.lang.String[] { "Begin", "End", });
    internal_static_Proj_Proto_EpochTime_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Proj_Proto_EpochTime_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_EpochTime_descriptor,
        new java.lang.String[] { "EpochId", "TimeValue", "TimeUnit", });
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    Proj.Google.LatLngProto.getDescriptor();
    Proj.Google.LocalizedTextProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
