// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientService.proto

package proj_contract.services;

public final class ClientServiceOuterClass {
  private ClientServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_ClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_ClientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientService.proto\022\nProj.Proto\032\020Conne" +
      "ction.proto\032\nData.proto\032\023LocationClaim.p" +
      "roto\032\031LocationEndorsement.proto\"?\n\016Clien" +
      "tResponse\022\027\n\017responseMessage\030\001 \001(\t\022\024\n\014re" +
      "sponseCode\030\002 \001(\0052\276\005\n\rClientService\022O\n\025re" +
      "questConnectionInfo\022\032.Proj.Proto.Connect" +
      "ionInfo\032\032.Proj.Proto.ClientResponse\022T\n\022s" +
      "endConnectionInfo\022\".Proj.Proto.Connectio" +
      "nInfoResponse\032\032.Proj.Proto.ClientRespons" +
      "e\022I\n\rsendSecretKey\022\034.Proj.Proto.SecretKe" +
      "yMessage\032\032.Proj.Proto.ClientResponse\022N\n\026" +
      "collectDataFromSensors\022\030.Proj.Proto.Enti" +
      "tiesData\032\032.Proj.Proto.ClientResponse\022J\n\022" +
      "updateTimestepData\022\030.Proj.Proto.Timestep" +
      "Data\032\032.Proj.Proto.ClientResponse\022S\n\021send" +
      "LocationClaim\022\".Proj.Proto.EncryptedLoca" +
      "tionClaim\032\032.Proj.Proto.ClientResponse\022i\n" +
      "\032requestLocationEndorsement\022/.Proj.Proto" +
      ".EncryptedLocationEndorsementRequest\032\032.P" +
      "roj.Proto.ClientResponse\022_\n\027sendLocation" +
      "Endorsement\022(.Proj.Proto.EncryptedLocati" +
      "onEndorsement\032\032.Proj.Proto.ClientRespons" +
      "eB\032\n\026proj_contract.servicesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proj_contract.services.Connection.getDescriptor(),
          proj_contract.proto.Data.getDescriptor(),
          proj_contract.proto.LocationClaimOuterClass.getDescriptor(),
          proj_contract.proto.LocationEndorsementOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_ClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_ClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_ClientResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    proj_contract.services.Connection.getDescriptor();
    proj_contract.proto.Data.getDescriptor();
    proj_contract.proto.LocationClaimOuterClass.getDescriptor();
    proj_contract.proto.LocationEndorsementOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
