// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientService.proto

package proj_contract.services;

public final class ClientServiceOuterClass {
  private ClientServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_ClientResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_ClientResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientService.proto\022\nProj.Proto\032\023Locat" +
      "ionClaim.proto\032\023CollectedData.proto\"?\n\016C" +
      "lientResponse\022\027\n\017responseMessage\030\001 \001(\t\022\024" +
      "\n\014responseCode\030\002 \001(\0052\356\001\n\rClientService\022M" +
      "\n\024receiveLocationClaim\022\031.Proj.Proto.Loca" +
      "tionClaim\032\032.Proj.Proto.ClientResponse\022J\n" +
      "\026collectDataFromSensors\022\024.Proj.Proto.Ent" +
      "ities\032\032.Proj.Proto.ClientResponse\022B\n\016upd" +
      "ateTimeStep\022\024.Proj.Proto.Position\032\032.Proj" +
      ".Proto.ClientResponseB\032\n\026proj_contract.s" +
      "ervicesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proj_contract.proto.LocationClaimProto.getDescriptor(),
          proj_contract.proto.CollectedDataProto.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_ClientResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_ClientResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_ClientResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    proj_contract.proto.LocationClaimProto.getDescriptor();
    proj_contract.proto.CollectedDataProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
