// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Connection.proto

package proj_contract.services;

public interface ConnectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.ConnectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();
}
