// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Connection.proto

package proj_contract.services;

public final class Connection {
  private Connection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_ConnectionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_ConnectionInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020Connection.proto\022\nProj.Proto\"M\n\016Connec" +
      "tionInfo\022\023\n\013requesterId\030\001 \001(\005\022\n\n\002id\030\002 \001(" +
      "\005\022\014\n\004port\030\003 \001(\005\022\014\n\004type\030\004 \001(\tB\032\n\026proj_co" +
      "ntract.servicesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Proj_Proto_ConnectionInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_ConnectionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_ConnectionInfo_descriptor,
        new java.lang.String[] { "RequesterId", "Id", "Port", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
