// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Connection.proto

package proj_contract.services;

public interface ConnectionInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.ConnectionInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Proj.Proto.ConnectionInfo connectionInfo = 1;</code>
   */
  boolean hasConnectionInfo();
  /**
   * <code>.Proj.Proto.ConnectionInfo connectionInfo = 1;</code>
   */
  proj_contract.services.ConnectionInfo getConnectionInfo();
  /**
   * <code>.Proj.Proto.ConnectionInfo connectionInfo = 1;</code>
   */
  proj_contract.services.ConnectionInfoOrBuilder getConnectionInfoOrBuilder();

  /**
   * <code>int32 requesterId = 2;</code>
   */
  int getRequesterId();
}
