// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerService.proto

package proj_contract.services;

public interface RegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Proj.Proto.RegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string type = 3;</code>
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 speed = 4;</code>
   */
  int getSpeed();
}
