// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerService.proto

package proj_contract.services;

public final class ServerServiceOuterClass {
  private ServerServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proj_Proto_ServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Proj_Proto_ServerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ServerService.proto\022\nProj.Proto\032\020Conne" +
      "ction.proto\032\023LocationClaim.proto\032\031Locati" +
      "onEndorsement.proto\032\016Register.proto\"?\n\016S" +
      "erverResponse\022\027\n\017responseMessage\030\001 \001(\t\022\024" +
      "\n\014responseCode\030\002 \001(\0052\341\004\n\rServerService\022X" +
      "\n\036broadcastConnectionInfoRequest\022\032.Proj." +
      "Proto.ConnectionInfo\032\032.Proj.Proto.Server" +
      "Response\022L\n\022sendConnectionInfo\022\032.Proj.Pr" +
      "oto.ConnectionInfo\032\032.Proj.Proto.ServerRe" +
      "sponse\022K\n\021requestConnection\022\032.Proj.Proto" +
      ".ConnectionInfo\032\032.Proj.Proto.ServerRespo" +
      "nse\022C\n\010register\022\033.Proj.Proto.RegisterReq" +
      "uest\032\032.Proj.Proto.ServerResponse\022P\n\021send" +
      "LocationClaim\022\037.Proj.Proto.LocationClaim" +
      "WithId\032\032.Proj.Proto.ServerResponse\022f\n\032re" +
      "questLocationEndorsement\022,.Proj.Proto.Lo" +
      "cationEndorsementRequestWithId\032\032.Proj.Pr" +
      "oto.ServerResponse\022\\\n\027sendLocationEndors" +
      "ement\022%.Proj.Proto.LocationEndorsementWi" +
      "thId\032\032.Proj.Proto.ServerResponseB\032\n\026proj" +
      "_contract.servicesP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proj_contract.services.Connection.getDescriptor(),
          proj_contract.proto.LocationClaimOuterClass.getDescriptor(),
          proj_contract.proto.LocationEndorsementOuterClass.getDescriptor(),
          proj_contract.services.Register.getDescriptor(),
        }, assigner);
    internal_static_Proj_Proto_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proj_Proto_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Proj_Proto_ServerResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    proj_contract.services.Connection.getDescriptor();
    proj_contract.proto.LocationClaimOuterClass.getDescriptor();
    proj_contract.proto.LocationEndorsementOuterClass.getDescriptor();
    proj_contract.services.Register.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
